SPC Sounding and Hodoraph Analysis and Research Program Calculation Library: convective_wrap.cpp File Reference
convective_wrap.cpp File Reference
#include <SHARPlib/CWrap/params/convective_wrap.h>
#include <SHARPlib/constants.h>
#include <SHARPlib/params/convective.h>
#include <stdlib.h>
Functions
void sharp_effective_inflow_layer (const float *pressure, const float *height, const float *temperature, const float *dewpoint, const float *virtemp_arr, const float *buoy_arr, const int N, sharp_PressureLayer_t *elyr, float cape_thresh, float cinh_thresh)
void sharp_storm_motion_bunkers_np (const float *pressure, const float *height, const float *u_wind, const float *v_wind, const int N, sharp_HeightLayer_t *mn_wind_lyr_agl, sharp_HeightLayer_t *wind_shr_lyr_agl, sharp_WindComponents_t *storm_motion, int leftMover, int pressureWeighted)
void sharp_storm_motion_bunkers (const float *pressure, const float *height, const float *u_wind, const float *v_wind, const int N, sharp_PressureLayer_t *eff_infl_lyr, sharp_Parcel_t *pcl, sharp_WindComponents_t *storm_motion, int leftMover)
float sharp_entrainment_cape (const float *pressure, const float *height, const float *temperature, const float *mse_arr, const float *u_wind, const float *v_wind, const int N, sharp_Parcel_t *pcl)
float sharp_energy_helicity_index (float cape, float helicity)
float sharp_supercell_composite_parameter (float mu_cape, float eff_srh, float eff_shear)
float sharp_significant_tornado_parameter (sharp_Parcel_t *pcl, float lcl_hght_agl, float helicity, float bulk_shear)
Function Documentation
sharp_effective_inflow_layer()
void sharp_effective_inflow_layer (const float * pressure, const float * height, const float * temperature, const float * dewpoint, const float * virtemp_arr, const float * buoy_arr, const int N, sharp_PressureLayer_t * elyr, float cape_thresh, float cinh_thresh)
Definition at line 7 of file convective_wrap.cpp.
{
    if (elyr == NULL) return;
    sharp::PressureLayer* l = static_cast<sharp::PressureLayer*>(elyr->obj);
    sharp::PressureLayer out = sharp::effective_inflow_layer(
        pressure, height, temperature, dewpoint, virtemp_arr, buoy_arr, N,
        cape_thresh, cinh_thresh);
    l->bottom = out.bottom;
    l->top = out.top;
}
References sharp::PressureLayer::bottom, sharp::effective_inflow_layer(), sharp_PressureLayer::obj, and sharp::PressureLayer::top.
sharp_energy_helicity_index()
float sharp_energy_helicity_index (float cape, float helicity)
Definition at line 77 of file convective_wrap.cpp.
{
    return sharp::energy_helicity_index(cape, helicity);
}
References sharp::energy_helicity_index().
sharp_entrainment_cape()
float sharp_entrainment_cape (const float * pressure, const float * height, const float * temperature, const float * mse_arr, const float * u_wind, const float * v_wind, const int N, sharp_Parcel_t * pcl)
Definition at line 67 of file convective_wrap.cpp.
{
    if ((pcl == NULL)) return sharp::MISSING;
    sharp::Parcel* pc = static_cast<sharp::Parcel*>(pcl->obj);
    return sharp::entrainment_cape(pressure, height, temperature, mse_arr,
                                   u_wind, v_wind, N, pc);
}
References sharp::entrainment_cape(), sharp::MISSING, and sharp_Parcel::obj.
sharp_significant_tornado_parameter()
float sharp_significant_tornado_parameter (sharp_Parcel_t * pcl, float lcl_hght_agl, float helicity, float bulk_shear)
Definition at line 86 of file convective_wrap.cpp.
{
    if ((pcl == NULL)) return sharp::MISSING;
    sharp::Parcel* pc = static_cast<sharp::Parcel*>(pcl->obj);
    return sharp::significant_tornado_parameter(*pc, lcl_hght_agl, helicity,
                                                bulk_shear);
}
References sharp::MISSING, sharp_Parcel::obj, and sharp::significant_tornado_parameter().
sharp_storm_motion_bunkers()
void sharp_storm_motion_bunkers (const float * pressure, const float * height, const float * u_wind, const float * v_wind, const int N, sharp_PressureLayer_t * eff_infl_lyr, sharp_Parcel_t * pcl, sharp_WindComponents_t * storm_motion, int leftMover)
Definition at line 48 of file convective_wrap.cpp.
{
    if ((storm_motion == NULL) || (pcl == NULL) || (eff_infl_lyr == NULL)) return;
    sharp::PressureLayer* eil =
        static_cast<sharp::PressureLayer*>(eff_infl_lyr->obj);
    sharp::Parcel* pc = static_cast<sharp::Parcel*>(pcl->obj);
    sharp::WindComponents* stm =
        static_cast<sharp::WindComponents*>(storm_motion->obj);
    sharp::WindComponents out = sharp::storm_motion_bunkers(
        pressure, height, u_wind, v_wind, N, eil, pcl, leftMover);
    stm->u = out.u;
    stm->v = out.v;
}
References sharp_PressureLayer::obj, sharp_Parcel::obj, sharp_WindComponents::obj, sharp::storm_motion_bunkers(), sharp::WindComponents::u, and sharp::WindComponents::v.
sharp_storm_motion_bunkers_np()
void sharp_storm_motion_bunkers_np (const float * pressure, const float * height, const float * u_wind, const float * v_wind, const int N, sharp_HeightLayer_t * mn_wind_lyr_agl, sharp_HeightLayer_t * wind_shr_lyr_agl, sharp_WindComponents_t * storm_motion, int leftMover, int pressureWeighted)
Definition at line 24 of file convective_wrap.cpp.
{
    if ((mn_wind_lyr_agl == NULL) || (wind_shr_lyr_agl == NULL) ||
        (storm_motion == NULL))
        return;
    sharp::HeightLayer* mnl =
        static_cast<sharp::HeightLayer*>(mn_wind_lyr_agl->obj);
    sharp::HeightLayer* shl =
        static_cast<sharp::HeightLayer*>(wind_shr_lyr_agl->obj);
    sharp::WindComponents* stm =
        static_cast<sharp::WindComponents*>(storm_motion->obj);
    sharp::WindComponents out =
        sharp::storm_motion_bunkers(pressure, height, u_wind, v_wind, N, *mnl,
                                    *shl, leftMover, pressureWeighted);
    stm->u = out.u;
    stm->v = out.v;
}
References sharp_HeightLayer::obj, sharp_WindComponents::obj, sharp::storm_motion_bunkers(), sharp::WindComponents::u, and sharp::WindComponents::v.
sharp_supercell_composite_parameter()
float sharp_supercell_composite_parameter (float mu_cape, float eff_srh, float eff_shear)
Definition at line 81 of file convective_wrap.cpp.
{
    return sharp::supercell_composite_parameter(mu_cape, eff_srh, eff_shear);
}
References sharp::supercell_composite_parameter().