SPC Sounding and Hodoraph Analysis and Research Program Calculation Library: layer_wrap.cpp File Reference
layer_wrap.cpp File Reference
#include <SHARPlib/CWrap/layer_wrap.h>
#include <SHARPlib/constants.h>
#include <SHARPlib/layer.h>
#include <stdlib.h>
Functions
sharp_PressureLayer_t * sharp_PressureLayer_create (float bottom, float top)
sharp_HeightLayer_t * sharp_HeightLayer_create (float bottom, float top)
sharp_LayerIndex_t * sharp_LayerIndex_create ()
void sharp_PressureLayer_delete (sharp_PressureLayer_t *l)
void sharp_HeightLayer_delete (sharp_HeightLayer_t *l)
void sharp_LayerIndex_delete (sharp_LayerIndex_t *i)
float sharp_PressureLayer_get_bottom (sharp_PressureLayer_t *l)
float sharp_PressureLayer_get_top (sharp_PressureLayer_t *l)
float sharp_HeightLayer_get_bottom (sharp_HeightLayer_t *l)
float sharp_HeightLayer_get_top (sharp_HeightLayer_t *l)
int sharp_LayerIndex_get_bottom (sharp_LayerIndex_t *i)
int sharp_LayerIndex_get_top (sharp_LayerIndex_t *i)
void sharp_get_PressureLayer_index (sharp_PressureLayer_t *lyr, sharp_LayerIndex_t *idx, const float *pressure, const int N)
void sharp_get_HeightLayer_index (sharp_HeightLayer_t *lyr, sharp_LayerIndex_t *idx, const float *height, const int N)
void sharp_HeightLayer_to_PressureLayer (sharp_HeightLayer_t *hlyr, sharp_PressureLayer_t *plyr, const float *pressure, const float *height, const int N, bool isAGL)
void sharp_PressureLayer_to_HeightLayer (sharp_PressureLayer_t *plyr, sharp_HeightLayer_t *hlyr, const float *pressure, const float *height, const int N, bool toAGL)
float sharp_PressureLayer_min (sharp_PressureLayer_t *plyr, const float *pres, const float *data, const int N, float *lvl_of_min)
float sharp_PressureLayer_max (sharp_PressureLayer_t *plyr, const float *pres, const float *data, const int N, float *lvl_of_max)
float sharp_HeightLayer_min (sharp_HeightLayer_t *hlyr, const float *hght, const float *data, const int N, float *lvl_of_min)
float sharp_HeightLayer_max (sharp_HeightLayer_t *hlyr, const float *hght, const float *data, const int N, float *lvl_of_max)
float sharp_PressureLayer_mean (sharp_PressureLayer_t *plyr, const float *pressure, const float *data, const int N)
float sharp_HeightLayer_mean (sharp_HeightLayer_t *hlyr, const float *height, const float *pressure, const float *data, const int N, int isAGL)
float sharp_PressureLayer_integrate (sharp_PressureLayer_t *plyr, const float *data, const float *pressure, const int N, int integ_sign, int weighted)
float sharp_HeightLayer_integrate (sharp_HeightLayer_t *hlyr, const float *data, const float *height, const int N, int integ_sign, int weighted)
Function Documentation
sharp_get_HeightLayer_index()
void sharp_get_HeightLayer_index (sharp_HeightLayer_t * lyr, sharp_LayerIndex_t * idx, const float * height, const int N)
Definition at line 95 of file layer_wrap.cpp.
{
    if ((lyr == NULL) || (idx == NULL)) return;
    sharp::HeightLayer* hl = static_cast<sharp::HeightLayer*>(lyr->obj);
    sharp::LayerIndex* i = static_cast<sharp::LayerIndex*>(idx->obj);
    sharp::LayerIndex out = sharp::get_layer_index(*hl, height, N);
    i->kbot = out.kbot;
    i->ktop = out.ktop;
}
References sharp::get_layer_index(), sharp::LayerIndex::kbot, sharp::LayerIndex::ktop, sharp_HeightLayer::obj, and sharp_LayerIndex::obj.
sharp_get_PressureLayer_index()
void sharp_get_PressureLayer_index (sharp_PressureLayer_t * lyr, sharp_LayerIndex_t * idx, const float * pressure, const int N)
Definition at line 84 of file layer_wrap.cpp.
{
    if ((lyr == NULL) || (idx == NULL)) return;
    sharp::PressureLayer* pl = static_cast<sharp::PressureLayer*>(lyr->obj);
    sharp::LayerIndex* i = static_cast<sharp::LayerIndex*>(idx->obj);
    sharp::LayerIndex out = sharp::get_layer_index(*pl, pressure, N);
    i->kbot = out.kbot;
    i->ktop = out.ktop;
}
References sharp::get_layer_index(), sharp::LayerIndex::kbot, sharp::LayerIndex::ktop, sharp_PressureLayer::obj, and sharp_LayerIndex::obj.
sharp_HeightLayer_create()
sharp_HeightLayer_t * sharp_HeightLayer_create (float bottom, float top)
Definition at line 16 of file layer_wrap.cpp.
{
    sharp_HeightLayer_t* l;
    sharp::HeightLayer* lyr;
    l = (sharp_HeightLayer_t*)malloc(sizeof(*l));
    lyr = new sharp::HeightLayer(bottom, top);
    l->obj = lyr;
    return l;
}
References sharp_HeightLayer::obj.
sharp_HeightLayer_delete()
void sharp_HeightLayer_delete (sharp_HeightLayer_t * l)
Definition at line 42 of file layer_wrap.cpp.
{
    if (l == NULL) return;
    delete static_cast<sharp::HeightLayer*>(l->obj);
    free(l);
}
References sharp_HeightLayer::obj.
sharp_HeightLayer_get_bottom()
float sharp_HeightLayer_get_bottom (sharp_HeightLayer_t * l)
Definition at line 64 of file layer_wrap.cpp.
{
    if (l == NULL) return sharp::MISSING;
    return static_cast<sharp::HeightLayer*>(l->obj)->bottom;
}
References sharp::MISSING, and sharp_HeightLayer::obj.
sharp_HeightLayer_get_top()
float sharp_HeightLayer_get_top (sharp_HeightLayer_t * l)
Definition at line 69 of file layer_wrap.cpp.
{
    if (l == NULL) return sharp::MISSING;
    return static_cast<sharp::HeightLayer*>(l->obj)->top;
}
References sharp::MISSING, and sharp_HeightLayer::obj.
sharp_HeightLayer_integrate()
float sharp_HeightLayer_integrate (sharp_HeightLayer_t * hlyr, const float * data, const float * height, const int N, int integ_sign, int weighted)
Definition at line 186 of file layer_wrap.cpp.
{
    sharp::HeightLayer* hl = static_cast<sharp::HeightLayer*>(hlyr->obj);
    return sharp::integrate_layer_trapz(*hl, data, height, N, integ_sign,
                                        weighted);
}
References sharp::integrate_layer_trapz(), and sharp_HeightLayer::obj.
sharp_HeightLayer_max()
float sharp_HeightLayer_max (sharp_HeightLayer_t * hlyr, const float * hght, const float * data, const int N, float * lvl_of_max)
Definition at line 157 of file layer_wrap.cpp.
{
    if (hlyr == NULL) return sharp::MISSING;
    sharp::HeightLayer* hl = static_cast<sharp::HeightLayer*>(hlyr->obj);
    return sharp::layer_max(*hl, hght, data, N, lvl_of_max);
}
References sharp::layer_max(), sharp::MISSING, and sharp_HeightLayer::obj.
sharp_HeightLayer_mean()
float sharp_HeightLayer_mean (sharp_HeightLayer_t * hlyr, const float * height, const float * pressure, const float * data, const int N, int isAGL)
Definition at line 171 of file layer_wrap.cpp.
{
    sharp::HeightLayer* hl = static_cast<sharp::HeightLayer*>(hlyr->obj);
    return sharp::layer_mean(*hl, height, pressure, data, N, isAGL);
}
References sharp::layer_mean(), and sharp_HeightLayer::obj.
sharp_HeightLayer_min()
float sharp_HeightLayer_min (sharp_HeightLayer_t * hlyr, const float * hght, const float * data, const int N, float * lvl_of_min)
Definition at line 150 of file layer_wrap.cpp.
{
    if (hlyr == NULL) return sharp::MISSING;
    sharp::HeightLayer* hl = static_cast<sharp::HeightLayer*>(hlyr->obj);
    return sharp::layer_min(*hl, hght, data, N, lvl_of_min);
}
References sharp::layer_min(), sharp::MISSING, and sharp_HeightLayer::obj.
sharp_HeightLayer_to_PressureLayer()
void sharp_HeightLayer_to_PressureLayer (sharp_HeightLayer_t * hlyr, sharp_PressureLayer_t * plyr, const float * pressure, const float * height, const int N, bool isAGL)
Definition at line 106 of file layer_wrap.cpp.
{
    if ((hlyr == NULL) || (plyr == NULL)) return;
    sharp::HeightLayer* hl = static_cast<sharp::HeightLayer*>(hlyr->obj);
    sharp::PressureLayer* pl = static_cast<sharp::PressureLayer*>(plyr->obj);
    sharp::PressureLayer out =
        sharp::height_layer_to_pressure(*hl, pressure, height, N, isAGL);
    hl->bottom = out.bottom;
    hl->top = out.top;
}
References sharp::HeightLayer::bottom, sharp::PressureLayer::bottom, sharp::height_layer_to_pressure(), sharp_PressureLayer::obj, sharp_HeightLayer::obj, sharp::HeightLayer::top, and sharp::PressureLayer::top.
sharp_LayerIndex_create()
sharp_LayerIndex_t * sharp_LayerIndex_create ()
Definition at line 26 of file layer_wrap.cpp.
{
    sharp_LayerIndex_t* i;
    sharp::LayerIndex* idx;
    i = (sharp_LayerIndex_t*)malloc(sizeof(*i));
    idx = new sharp::LayerIndex();
    i->obj = idx;
    return i;
}
References sharp_LayerIndex::obj.
sharp_LayerIndex_delete()
void sharp_LayerIndex_delete (sharp_LayerIndex_t * i)
Definition at line 48 of file layer_wrap.cpp.
{
    if (i == NULL) return;
    delete static_cast<sharp::LayerIndex*>(i->obj);
    free(i);
}
References sharp_LayerIndex::obj.
sharp_LayerIndex_get_bottom()
int sharp_LayerIndex_get_bottom (sharp_LayerIndex_t * i)
Definition at line 74 of file layer_wrap.cpp.
{
    if (i == NULL) return 0;
    return static_cast<sharp::LayerIndex*>(i->obj)->kbot;
}
References sharp_LayerIndex::obj.
sharp_LayerIndex_get_top()
int sharp_LayerIndex_get_top (sharp_LayerIndex_t * i)
Definition at line 79 of file layer_wrap.cpp.
{
    if (i == NULL) return 0;
    return static_cast<sharp::LayerIndex*>(i->obj)->ktop;
}
References sharp_LayerIndex::obj.
sharp_PressureLayer_create()
sharp_PressureLayer_t * sharp_PressureLayer_create (float bottom, float top)
Definition at line 6 of file layer_wrap.cpp.
{
    sharp_PressureLayer_t* l;
    sharp::PressureLayer* lyr;
    l = (sharp_PressureLayer_t*)malloc(sizeof(*l));
    lyr = new sharp::PressureLayer(bottom, top);
    l->obj = lyr;
    return l;
}
References sharp_PressureLayer::obj.
sharp_PressureLayer_delete()
void sharp_PressureLayer_delete (sharp_PressureLayer_t * l)
Definition at line 36 of file layer_wrap.cpp.
{
    if (l == NULL) return;
    delete static_cast<sharp::PressureLayer*>(l->obj);
    free(l);
}
References sharp_PressureLayer::obj.
sharp_PressureLayer_get_bottom()
float sharp_PressureLayer_get_bottom (sharp_PressureLayer_t * l)
Definition at line 54 of file layer_wrap.cpp.
{
    if (l == NULL) return sharp::MISSING;
    return static_cast<sharp::PressureLayer*>(l->obj)->bottom;
}
References sharp::MISSING, and sharp_PressureLayer::obj.
sharp_PressureLayer_get_top()
float sharp_PressureLayer_get_top (sharp_PressureLayer_t * l)
Definition at line 59 of file layer_wrap.cpp.
{
    if (l == NULL) return sharp::MISSING;
    return static_cast<sharp::PressureLayer*>(l->obj)->top;
}
References sharp::MISSING, and sharp_PressureLayer::obj.
sharp_PressureLayer_integrate()
float sharp_PressureLayer_integrate (sharp_PressureLayer_t * plyr, const float * data, const float * pressure, const int N, int integ_sign, int weighted)
Definition at line 178 of file layer_wrap.cpp.
{
    sharp::PressureLayer* pl = static_cast<sharp::PressureLayer*>(plyr->obj);
    return sharp::integrate_layer_trapz(*pl, data, pressure, N, integ_sign,
                                        weighted);
}
References sharp::integrate_layer_trapz(), and sharp_PressureLayer::obj.
sharp_PressureLayer_max()
float sharp_PressureLayer_max (sharp_PressureLayer_t * plyr, const float * pres, const float * data, const int N, float * lvl_of_max)
Definition at line 143 of file layer_wrap.cpp.
{
    if (plyr == NULL) return sharp::MISSING;
    sharp::PressureLayer* pl = static_cast<sharp::PressureLayer*>(plyr->obj);
    return sharp::layer_max(*pl, pres, data, N, lvl_of_max);
}
References sharp::layer_max(), sharp::MISSING, and sharp_PressureLayer::obj.
sharp_PressureLayer_mean()
float sharp_PressureLayer_mean (sharp_PressureLayer_t * plyr, const float * pressure, const float * data, const int N)
Definition at line 164 of file layer_wrap.cpp.
{
    sharp::PressureLayer* pl = static_cast<sharp::PressureLayer*>(plyr->obj);
    return sharp::layer_mean(*pl, pressure, data, N);
}
References sharp::layer_mean(), and sharp_PressureLayer::obj.
sharp_PressureLayer_min()
float sharp_PressureLayer_min (sharp_PressureLayer_t * plyr, const float * pres, const float * data, const int N, float * lvl_of_min)
Definition at line 136 of file layer_wrap.cpp.
{
    if (plyr == NULL) return sharp::MISSING;
    sharp::PressureLayer* pl = static_cast<sharp::PressureLayer*>(plyr->obj);
    return sharp::layer_min(*pl, pres, data, N, lvl_of_min);
}
References sharp::layer_min(), sharp::MISSING, and sharp_PressureLayer::obj.
sharp_PressureLayer_to_HeightLayer()
void sharp_PressureLayer_to_HeightLayer (sharp_PressureLayer_t * plyr, sharp_HeightLayer_t * hlyr, const float * pressure, const float * height, const int N, bool toAGL)
Definition at line 121 of file layer_wrap.cpp.
{
    if ((hlyr == NULL) || (plyr == NULL)) return;
    sharp::PressureLayer* pl = static_cast<sharp::PressureLayer*>(plyr->obj);
    sharp::HeightLayer* hl = static_cast<sharp::HeightLayer*>(hlyr->obj);
    sharp::HeightLayer out =
        sharp::pressure_layer_to_height(*pl, pressure, height, N, toAGL);
    pl->bottom = out.bottom;
    pl->top = out.top;
}
References sharp::HeightLayer::bottom, sharp::PressureLayer::bottom, sharp_PressureLayer::obj, sharp_HeightLayer::obj, sharp::pressure_layer_to_height(), sharp::HeightLayer::top, and sharp::PressureLayer::top.