SPC Sounding and Hodoraph Analysis and Research Program Calculation Library: sharp Namespace Reference
sharp Namespace Reference
Namespaces
namespace exper
Classes
struct HeightLayer
A simple structure of named floats that represent a height layer.
struct LayerIndex
A simple structure of two named integer indices for the top and bottom of a layer.
struct lifter_cm1
struct lifter_wobus
A functor that calls the Wobus Wetlift funtion.
struct Parcel
Data that defines a Parcel, its attributes, and derived quantities.
struct PressureLayer
A simple structure of two named floats that represent a pressure layer.
struct WindComponents
A simple structure of two names floats that represent the components of a wind vector.
struct WindVector
A simple structure of two named floats that represent a wind vector.
Enumerations
enum class LayerCoordinate { height = 0 , pressure = 1 , END }
Enum defining the coordinate system of a layer.
enum class LPL : int {
SFC = 1 , FCST = 2 , MU = 3 , ML = 4 ,
USR = 5 , END
}
Enum that defines the lifted parcel level (LPL) of origin.
enum class adiabat : int {
pseudo_liq = 1 , adiab_liq = 2 , pseudo_ice = 3 , adiab_ice = 4 ,
END
}
Defines the kinds of moist adiabats used by sharp::moist_adiabat_cm1.
Functions
template<typename T , typename C = std::less<>>
constexpr std::ptrdiff_t lower_bound (const T array[], const std::ptrdiff_t N, const T value, const C cmp=C{})
Finds the index of the lower bound that does not satisfy element < value.
template<typename T , typename C = std::less<>>
constexpr std::ptrdiff_t upper_bound (const T array[], const std::ptrdiff_t N, const T value, const C cmp=C{})
Finds the first index that satisfies value < element.
template<typename _T >
constexpr _T _integ_trapz (_T var_top, _T var_bottom, _T coord_top, _T coord_bottom, _T &weights, const bool weighted=false)
A kernel that computes the area under a curve using the trapezoidal rule.
template<typename _Fp >
constexpr _Fp __lerp (const _Fp __a, const _Fp __b, const _Fp __t)
Linearly interpolates between a and b with distance t.
constexpr float lerp (const float __a, const float __b, const float __t)
Linearly interpolates between a and b with distance t.
float interp_height (const float height_val, const float height_arr[], const float data_arr[], const std::ptrdiff_t N)
Linearly interpolate a data field to a requested height level.
float interp_pressure (const float pressure_val, const float pressure_arr[], const float data_arr[], const std::ptrdiff_t N)
Linearly interpolate a data field to a requested pressure level.
template<typename L , typename Cb , typename Ct >
constexpr LayerIndex get_layer_index (L &layer, const float coord[], const std::ptrdiff_t N, const Cb bottom_comp, const Ct top_comp)
Returns the array indices corresponding to the given layer.
LayerIndex get_layer_index (PressureLayer &layer, const float pressure[], const std::ptrdiff_t N)
Finds the array indices corresponding to the given sharp::PressureLayer.
LayerIndex get_layer_index (HeightLayer &layer, const float height[], const std::ptrdiff_t N)
Finds the array indices corresponding to the given sharp::HeightLayer.
PressureLayer height_layer_to_pressure (HeightLayer layer, const float pressure[], const float height[], const std::ptrdiff_t N, const bool isAGL=false)
Converts a sharp::HeightLayer to a sharp::PressureLayer.
HeightLayer pressure_layer_to_height (PressureLayer layer, const float pressure[], const float height[], const std::ptrdiff_t N, const bool toAGL=false)
Converts a sharp::PressureLayer to a sharp::HeightLayer.
template<typename L , typename C >
constexpr float layer_minmax (L layer, const float coord_arr[], const float data_arr[], const std::ptrdiff_t N, float *lvl_min_or_max, const C comp)
Template for min/max value over sharp::PressureLayer or sharp::HeightLayer.
template<typename L >
constexpr float layer_min (L layer, const float coord_arr[], const float data_arr[], const std::ptrdiff_t N, float *lvl_of_min=nullptr)
Returns the minimum value in the given layer.
template<typename L >
constexpr float layer_max (L layer, const float coord_arr[], const float data_arr[], const std::ptrdiff_t N, float *lvl_of_max=nullptr)
Returns the maximim value in the given layer.
template<typename L >
float integrate_layer_trapz (L layer, const float var_array[], const float coord_array[], const std::ptrdiff_t N, const int integ_sign=0, const bool weighted=false)
Returns a trapezoidal integration of the given layer.
float layer_mean (PressureLayer layer, const float pressure[], const float data_arr[], const std::ptrdiff_t N)
Computes the mass-weighted mean value of a field over a given pressure layer.
float layer_mean (HeightLayer layer, const float height[], const float pressure[], const float data_arr[], const std::ptrdiff_t N, const bool isAGL=false)
Computes the mass-weighted mean value of a field over a given height layer.
template<typename Lifter >
PressureLayer effective_inflow_layer (Lifter &lifter, const float pressure[], const float height[], const float temperature[], const float dewpoint[], const float virtemp_arr[], float pcl_vtmpk_arr[], float buoy_arr[], const std::ptrdiff_t N, const float cape_thresh=100.0, const float cinh_thresh=-250.0, Parcel *mupcl=nullptr)
Computes the Effective Inflow Layer for a given atmospheric sounding.
WindComponents storm_motion_bunkers (const float pressure[], const float height[], const float u_wind[], const float v_wind[], const std::ptrdiff_t N, HeightLayer mean_wind_layer_agl, HeightLayer wind_shear_layer_agl, const bool leftMover=false, const bool pressureWeighted=false)
Estimates supercell storm motion using the Bunkers et al. 2000 method.
WindComponents storm_motion_bunkers (const float pressure[], const float height[], const float u_wind[], const float v_wind[], const std::ptrdiff_t N, PressureLayer eff_infl_lyr, const Parcel *mupcl, const bool leftMover=false)
Estimates supercell storm motion by using the Bunkers et al. 2014 method.
float entrainment_cape (const float pressure[], const float height[], const float temperature[], const float mse_arr[], const float u_wind[], const float v_wind[], const std::ptrdiff_t N, Parcel *pcl)
Computes Entrainment CAPE using a previously lifted parcel.
float energy_helicity_index (float cape, float helicity)
float supercell_composite_parameter (float mu_cape, float eff_srh, float eff_shear)
float significant_tornado_parameter (Parcel pcl, float lcl_hght_agl, float storm_relative_helicity, float bulk_wind_difference)
float wobf (float temperature)
Computes the difference between the wet-bulb potential temperatures for saturated and dry air given the temperature.
float vapor_pressure (float pressure, float temperature)
Compute the vapor pressure over liquid water.
float vapor_pressure_ice (float pressure, float temperature)
Compute the vapor pressure over ice.
float lcl_temperature (float temperature, float dewpoint)
Compute the temperature of the LCL.
float temperature_at_mixratio (float wv_mixratio, float pressure)
Compute the temperature at a given water vapor mixing ratio and pressure level.
float theta_level (float potential_temperature, float temperature)
Comute the pressure level given potential temperature and temperature.
float theta (float pressure, float temperature, float ref_pressure=THETA_REF_PRESSURE)
Compute the potential temperature.
float mixratio (float q)
Compute the water vapor mixing ratio from specific humidity.
float mixratio (float pressure, float temperature)
Compute the water vapor mixing ratio.
float mixratio_ice (float pressure, float temperature)
Compute the ice water mixing ratio.
float specific_humidity (float rv)
Compute specific humidity from a mixing ratio.
float virtual_temperature (float temperature, float rv, float rl=0.0f, float ri=0.0f)
Compute the full virtual temperature.
float saturated_lift (float pressure, float theta_sat, float converge=0.001f)
Compute the temperature along a moist adiabat (wet-bulb potential temperature) at a given pressure.
float wetlift (float pressure, float temperature, float lifted_pressure)
Compute the temperature of a parcel lifted moist adiabatically to a new level.
float moist_adiabat_cm1 (float pressure, float temperature, float new_pressure, float &rv_total, float &rv, float &rl, float &ri, float pres_incr, float converge, adiabat ma_type)
Compute the temperature of a parcel lifted moist adiabatically to a new level.
void drylift (float pressure, float temperature, float dewpoint, float &pressure_at_lcl, float &temperature_at_lcl)
Lift a parcel dry adiabatically to its Lifted Condensation Level (LCL).
template<typename Lft >
float wetbulb (Lft lifter, float pressure, float temperature, float dewpoint)
Compute the wetbulb temperature.
template<typename Lft >
float theta_wetbulb (Lft lifter, float pressure, float temperature, float dewpoint)
Compute the wetbulb potential temperature.
float thetae (float pressure, float temperature, float dewpoint)
Compute the equivalent potential temperature.
float lapse_rate (HeightLayer layer_agl, const float height[], const float temperature[], const std::ptrdiff_t N)
compute the lapse rate over the given sharp::HeightLayer (AGL)
float lapse_rate (PressureLayer layer, const float pressure[], const float height[], const float temperature[], const std::ptrdiff_t N)
compute the lapse rate over the given sharp::PressureLayer
float lapse_rate_max (HeightLayer layer_agl, const float depth, const float height[], const float temperature[], const std::ptrdiff_t N, HeightLayer *max_lyr=nullptr)
Find the maximum lapse rate within a specified layer/depth (AGL).
float lapse_rate_max (PressureLayer layer, const float depth, const float pressure[], const float height[], const float temperature[], const std::ptrdiff_t N, PressureLayer *max_lyr=nullptr)
Find the maximum lapse rate within a specified layer/depth (Pres)
float buoyancy (const float pcl_temperature, const float env_temperature)
compute buoyancy given parcel and environment temperatures
void buoyancy (const float pcl_temperature[], const float env_temperature[], float buoy_arr[], std::ptrdiff_t N)
Compute buoyancy given arrays of parcel & environment temperatures.
float moist_static_energy (float height_agl, float temperature, float specific_humidity)
Compute moist static energy.
float buoyancy_dilution_potential (const float temperature, const float mse_bar, const float saturation_mse)
float u_component (float wind_speed, float wind_direction)
Computes the zonal (U) wind component from a wind vector.
float v_component (float wind_speed, float wind_direction)
Computes the meridional (V) wind component from a wind vector.
float vector_angle (float u_comp, float v_comp)
Computes the direction (degrees from North) a vector points to.
float vector_magnitude (float u_comp, float v_comp)
Computes the magnitude of a vector given its components.
float vector_magnitude_precise (float u_comp, float v_comp)
Precisely computes the magnitude of a vector given its components.
WindVector components_to_vector (float u_comp, float v_comp)
Conveniance function to compute wind speed and direction from components.
WindVector components_to_vector (WindComponents comp)
Conveniance function to compute wind speed and direction from components.
WindComponents vector_to_components (float wind_speed, float wind_direction)
Conveniance function to compute the U and V components of a wind vector.
WindComponents vector_to_components (WindVector vect)
Conveniance function to compute the U and V components of a wind vector.
WindComponents mean_wind (PressureLayer layer, const float pres[], const float u_wind[], const float v_wind[], const std::ptrdiff_t N, const bool weighted)
Compute the mean wind over the given sharp::PressureLayer.
template<typename L >
constexpr WindComponents wind_shear (L layer, const float coord[], const float u_wind[], const float v_wind[], const std::ptrdiff_t N)
Compue the wind shear for a given layer.
template<typename L >
float helicity (L layer, WindComponents storm_motion, const float coord[], const float u_wind[], const float v_wind[], const std::ptrdiff_t N)
Computes the Storm Relative Helicity (SRH) over a given layer.
PressureLayer effective_inflow_layer (sharp::lifter_wobus &lifter, const float pressure[], const float height[], const float temperature[], const float dewpoint[], const float virtemp_arr[], float pcl_vtmpk_arr[], float buoy_arr[], const std::ptrdiff_t N, const float cape_thresh, const float cinh_thresh, Parcel *mupcl)
PressureLayer effective_inflow_layer (sharp::lifter_cm1 &lifter, const float pressure[], const float height[], const float temperature[], const float dewpoint[], const float virtemp_arr[], float pcl_vtmpk_arr[], float buoy_arr[], const std::ptrdiff_t N, const float cape_thresh, const float cinh_thresh, Parcel *mupcl)
float _solve_cm1 (float &pcl_pres_next, float &pcl_pi_next, float &pcl_t_next, float &pcl_rv_next, float &pcl_rl_next, float &pcl_ri_next, float pcl_pres_prev, float pcl_t_prev, float pcl_theta_prev, float pcl_rv_prev, float pcl_rl_prev, float pcl_ri_prev, float rv_total, bool ascending, bool ice=false, float converge=0.0002f)
float wetbulb (lifter_wobus lifter, float pressure, float temperature, float dewpoint)
float wetbulb (lifter_cm1 lifter, float pressure, float temperature, float dewpoint)
float theta_wetbulb (lifter_wobus lifter, float pressure, float temperature, float dewpoint)
float theta_wetbulb (lifter_cm1 lifter, float pressure, float temperature, float dewpoint)
Variables
static constexpr float RGAS = 8.314462618f
static constexpr float MDRY = 28.96546e-3f
static constexpr float MWATER = 18.015268e-3f
static constexpr float DRYAIR_SPEC_HEAT_RATIO = 1.4f
static constexpr float ZEROCNK = 273.15f
static constexpr float HPA_TO_PA = 100.0f
static constexpr float PA_TO_HPA = 0.01f
static constexpr float THETA_REF_PRESSURE = 100000.0f
static constexpr float MISSING = -9999.0f
static constexpr float GRAVITY = 9.80665f
static constexpr float TOL = 1e-10f
static constexpr float PI = 3.14159265f
static constexpr float RDGAS = RGAS / MDRY
static constexpr float RVGAS = RGAS / MWATER
static constexpr float EPSILON = RDGAS / RVGAS
static constexpr float CP_DRYAIR
static constexpr float CP_VAPOR = 1875.0f
static constexpr float CP_LIQUID = 4190.0f
static constexpr float CP_ICE = 2118.636f
static constexpr float EXP_LV = 2.501e6f
static constexpr float EXP_LS = 2.836017e6f
static constexpr float LV1 = EXP_LV + (CP_LIQUID - CP_VAPOR) * ZEROCNK
static constexpr float LV2 = CP_LIQUID - CP_VAPOR
static constexpr float LS1 = EXP_LS + (CP_ICE - CP_VAPOR) * ZEROCNK
static constexpr float LS2 = CP_ICE - CP_VAPOR
static constexpr float ROCP = RDGAS / CP_DRYAIR
static constexpr float GAMMA_D = GRAVITY / CP_DRYAIR
static constexpr float PRANDTL = 1.f / 3.f
static constexpr float VKSQ = 0.18f
static constexpr float VAPPRES_REF = 611.65f
Enumeration Type Documentation
adiabat
enum class sharp::adiabat : int strong
Defines the kinds of moist adiabats used by sharp::moist_adiabat_cm1.
Enumerator
pseudo_liq
Pseudoadiabatic considering only liquid water.
adiab_liq
Adiabatic considering only liquid water.
pseudo_ice
Pseudoadiabatic considering liquid water + ice.
adiab_ice
Adiabatic considering liquid water + ice.
END
Definition at line 29 of file thermo.h.
                   : int {
    pseudo_liq = 1,
    adiab_liq = 2,
    pseudo_ice = 3,
    adiab_ice = 4,
    END,
};
LayerCoordinate
enum class sharp::LayerCoordinate strong
Enum defining the coordinate system of a layer.
Author
Kelton Halbert - NWS Storm Prediction Center
Enumerator
height
Height coordinate.
pressure
Pressure coordinate.
END
End value for range checking parameters.
Definition at line 33 of file layer.h.
{
    height = 0,
    pressure = 1,
    END,
};
LPL
enum class sharp::LPL : int strong
Enum that defines the lifted parcel level (LPL) of origin.
The SFC parcel is a surface-based parcel, where the parcel initial attributes are set to the surface pressure, temperature, and dewpoint.
The FCST parcel is a forecast-surface-based parcel, in which the afternoon surface temperature and dewpoint are estimated and set as the parcel starting values.
The MU parcel is the most unstable parcel, in which the parcel attributes are set to the pressure, temperature, and dewpoint of the maximum Theta-E level within the bottom 400 hPa of the profile.
The ML parcel is the mixed-layer parcel, in which the mean theta and water vapor mixing ratio within the lowest 100 hPa are used to estimate a boundary layer mean, and lifted from the surface.
The USR parcel means that the parcel initial lifting attributes have already been set by the programmer or user, and there is no need for them to be set or modified.
Enumerator
SFC
Surface Based Parcel.
FCST
Forecast Surface Parcel.
MU
Most Unstable Parcel.
ML
Mixed Layer Parcel.
USR
User-defined Parcel.
END
Definition at line 195 of file parcel.h.
               : int {
    SFC = 1,
    FCST = 2,
    MU = 3,  // most unstable
    ML = 4,  // Mixed layer
    USR = 5,  // user-defined
    END,
};
Function Documentation
__lerp()
template<typename _Fp > constexpr _Fp sharp::__lerp (const _Fp __a, const _Fp __b, const _Fp __t) constexpr
Linearly interpolates between a and b with distance t.
Author
C++20 Standard Template Library
This routine was copied from the C++20 standard template library. It is used to linearly interpolate between A and B over a normalized distance T, where 0 <= T <= 1. Full documentation and details can be found in the paper located here: https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0811r3.html
This linear interpolation guarantees the following:
Exactness: lerp(a,b,0)==a & lerp(a,b,1)==b
Monotonicity: cmp(lerp(a,b,t2), lerp(a,b,t1)) * cmp(t2, t1)
cmp(b,a) >= 0, where cmp is an arithmetic three-way comparison function
Determinacy: result of NaN only for lerp(a,a,INFINITY)
Boundedness: t<0 || t>1 || isfinite(lerp(a,b,t))
Consistency: lerp(a,a,t) == a
Parameters
__a left value
__b right value
__t where 0 <= __t <= 1.0
Returns
The value between __a and __b at distance __t between them.
Definition at line 51 of file interp.h.
{
    if ((__a <= 0 && __b >= 0) || (__a >= 0 && __b <= 0))
        return __t * __b + (1 - __t) * __a;
    if (__t == 1) return __b;  // exact
    // Exact at __t=0, monotonic except near __t=1,
    // bounded, determinate, and consistent:
    const _Fp __x = __a + __t * (__b - __a);
    return (__t > 1) == (__b > __a)
               ? (__b < __x ? __x : __b)
               : (__b > __x ? __x : __b);  // monotonic near __t=1
}
Referenced by lerp().
_integ_trapz()
template<typename _T > constexpr _T sharp::_integ_trapz (_T var_top, _T var_bottom, _T coord_top, _T coord_bottom, _T & weights, const bool weighted = false) inline constexpr
A kernel that computes the area under a curve using the trapezoidal rule.
Author
Kelton Halbert - NWS Storm Prediction Center
This is a function kernel that integrates an area using the trapezoidal rule. This function does not do the actual integration over an array, but is meant to be wrapped by any function that does so.
Parameters
var_top The top value of the variable to integrate
var_bottom The bottom value of the variable to integrate
coord_top The top value of the coordinate to integrate
coord_bottom The bottom value of the coordinate to integrate
weights The weights to accumulate
weighted Whether or not to accumulate weights
Returns
The area under the curve
Definition at line 125 of file algorithms.h.
{
    weights += (weighted) * (coord_top - coord_bottom);
    return ((var_top + var_bottom) / 2.0f) * (coord_top - coord_bottom);
}
Referenced by integrate_layer_trapz().
_solve_cm1()
float sharp::_solve_cm1 (float & pcl_pres_next, float & pcl_pi_next, float & pcl_t_next, float & pcl_rv_next, float & pcl_rl_next, float & pcl_ri_next, float pcl_pres_prev, float pcl_t_prev, float pcl_theta_prev, float pcl_rv_prev, float pcl_rl_prev, float pcl_ri_prev, float rv_total, bool ascending, bool ice = false, float converge = 0.0002f)
Definition at line 223 of file thermo.cpp.
{
    // first guess - use the theta of the parcel
    // before lifting, and update the first guess
    // accordingly
    float pcl_theta_last = pcl_theta_prev;
    float pcl_theta_next = pcl_theta_prev;
    bool not_converged = true;
    while (not_converged) {
        pcl_t_next = pcl_theta_last * pcl_pi_next;
        float fliq = 1.0;
        float fice = 0.0;
        if (ice) {
            fliq = std::max(
                std::min((pcl_t_next - 233.15f) / (ZEROCNK - 233.15f), 1.0f),
                0.0f);
            fice = 1.0f - fliq;
        }
        const float rv_term = fliq * mixratio(pcl_pres_next, pcl_t_next) +
                              fice * mixratio_ice(pcl_pres_next, pcl_t_next);
        if (ascending) {
            pcl_rv_next = std::min(rv_total, rv_term);
            pcl_ri_next = std::max(fice * (rv_total - pcl_rv_next), 0.0f);
            pcl_rl_next = std::max(rv_total - pcl_rv_next - pcl_ri_next, 0.0f);
        } else {
            pcl_rv_next = rv_term;
            pcl_rl_next = fliq * (rv_total - pcl_rv_next);
            pcl_ri_next = fice * (rv_total - pcl_rv_next);
        }
        const float tbar = 0.5f * (pcl_t_prev + pcl_t_next);
        const float rvbar = 0.5f * (pcl_rv_prev + pcl_rv_next);
        const float rlbar = 0.5f * (pcl_rl_prev + pcl_rl_next);
        const float ribar = 0.5f * (pcl_ri_prev + pcl_ri_next);
        const float LHV = LV1 - LV2 * tbar;
        const float LHS = LS1 - LS2 * tbar;
        const float RM = RDGAS + RVGAS * rvbar;
        const float CPM =
            CP_DRYAIR + CP_VAPOR * rvbar + CP_LIQUID * rlbar + CP_ICE * ribar;
        const float term =
            LHV * (pcl_rl_next - pcl_rl_prev) / (CPM * tbar) +
            LHS * (pcl_ri_next - pcl_ri_prev) / (CPM * tbar) +
            (RM / CPM - ROCP) * std::log(pcl_pres_next / pcl_pres_prev);
        pcl_theta_next = pcl_theta_prev * std::exp(term);
        if (std::abs(pcl_theta_next - pcl_theta_last) > converge) {
            pcl_theta_last =
                pcl_theta_last + 0.3 * (pcl_theta_next - pcl_theta_last);
        } else {
            not_converged = false;
        }
    }
    return pcl_theta_next;
}
References CP_DRYAIR, CP_ICE, CP_LIQUID, CP_VAPOR, LS1, LS2, LV1, LV2, mixratio(), mixratio_ice(), RDGAS, ROCP, RVGAS, and ZEROCNK.
Referenced by moist_adiabat_cm1().
buoyancy() [1/2]
float sharp::buoyancy (const float pcl_temperature, const float env_temperature)
compute buoyancy given parcel and environment temperatures
Author
Kelton Halbert - NWS Storm Prediction Center
Parameters
pcl_temperature (K)
env_temperature (K)
Returns
buoyancy (m/s^2)
Definition at line 506 of file thermo.cpp.
{
    return GRAVITY * (pcl_temperature - env_temperature) / (env_temperature);
}
References GRAVITY.
Referenced by buoyancy(), effective_inflow_layer(), sharp::Parcel::most_unstable_parcel(), and sharp_buoyancy().
buoyancy() [2/2]
void sharp::buoyancy (const float pcl_temperature[], const float env_temperature[], float buoy_arr[], std::ptrdiff_t N)
Compute buoyancy given arrays of parcel & environment temperatures.
Author
Kelton Halbert - NWS Storm Prediction Center
Parameters
pcl_temperature (K)
env_temperature (K)
buoy_arr Output array to fill with buoyancy
N Length of arrays
Definition at line 510 of file thermo.cpp.
{
    for (std::ptrdiff_t k = 0; k < N; ++k) {
        buoy_arr[k] = buoyancy(pcl_temperature[k], env_temperature[k]);
    }
}
References buoyancy().
buoyancy_dilution_potential()
float sharp::buoyancy_dilution_potential (const float temperature, const float mse_bar, const float saturation_mse)
Definition at line 530 of file thermo.cpp.
{
#ifndef NO_QC
    if ((temperature == MISSING) || (mse_bar == MISSING) ||
        (saturation_mse == MISSING)) {
        return MISSING;
    }
#endif
    return -1.0f * (GRAVITY / (CP_DRYAIR * temperature)) *
           (mse_bar - saturation_mse);
}
References CP_DRYAIR, GRAVITY, and MISSING.
Referenced by entrainment_cape(), and sharp_buoyancy_dilution_potential().
components_to_vector() [1/2]
WindVector sharp::components_to_vector (float u_comp, float v_comp)
Conveniance function to compute wind speed and direction from components.
Author
Kelton Halbert - NWS Storm Prediction Center
Given the zonal (U) and meridional (V) components of a vector, compute and return the wind speed (m/s) and direction (degrees from North) from the components as a struct.
Parameters
u_comp (m/s)
v_comp (m/s)
Returns
{wind_speed, wind_direction}
Definition at line 66 of file winds.cpp.
{
    const float wind_speed = vector_magnitude(u_comp, v_comp);
    const float wind_direction = vector_angle(u_comp, v_comp);
    return {wind_speed, wind_direction};
}
References vector_angle(), and vector_magnitude().
Referenced by sharp_components_to_vector().
components_to_vector() [2/2]
WindVector sharp::components_to_vector (WindComponents comp)
Conveniance function to compute wind speed and direction from components.
Author
Kelton Halbert - NWS Storm Prediction Center
Given the components of a vector via sharp::WindComponents, compute and return the wind speed (m/s) and direction (degrees from North) and return them as sharp::WindVector.
Parameters
comp {u_comp, v_comp}
Returns
{wind_speed, wind_direction}
Definition at line 73 of file winds.cpp.
{
    const float wind_speed = vector_magnitude(comp.u, comp.v);
    const float wind_direction = vector_angle(comp.u, comp.v);
    return {wind_speed, wind_direction};
}
References sharp::WindComponents::u, sharp::WindComponents::v, vector_angle(), and vector_magnitude().
drylift()
void sharp::drylift (float pressure, float temperature, float dewpoint, float & pressure_at_lcl, float & temperature_at_lcl)
Lift a parcel dry adiabatically to its Lifted Condensation Level (LCL).
Author
John Hart - NSSFC KCMO / NWSSPC OUN
Given a parcel's initial pressure (Pa), temperature (K), and dewpoint temperature (K), lift the parcel dry adiabatically to its Lifted Condensation Level and store the resulting LCL pressure (Pa) and LCL temperature (K) in the variables passed by reference to the routine.
The LCL temperature is computed using an approximation. See the sharp::lcl_temperature documentation for more information.
Parameters
pressure (Pa)
temperature (K)
dewpoint (K)
pressure_at_lcl (Pa)
temperature_at_lcl (K)
Definition at line 351 of file thermo.cpp.
{
#ifndef NO_QC
    if ((pressure == MISSING) || (temperature == MISSING) ||
        (dewpoint == MISSING)) {
        pressure_at_lcl = MISSING;
        temperature_at_lcl = MISSING;
        return;
    }
#endif
    // theta is constant from parcel level to LCL
    const float pcl_theta = theta(pressure, temperature, THETA_REF_PRESSURE);
    temperature_at_lcl = lcl_temperature(temperature, dewpoint);
    pressure_at_lcl = theta_level(pcl_theta, temperature_at_lcl);
    if (pressure_at_lcl > pressure) pressure_at_lcl = pressure;
    return;
}
References lcl_temperature(), MISSING, pressure, theta(), theta_level(), and THETA_REF_PRESSURE.
Referenced by sharp::Parcel::lift_parcel(), sharp_drylift(), theta_wetbulb(), thetae(), and wetbulb().
effective_inflow_layer() [1/3]
template<typename Lifter > PressureLayer sharp::effective_inflow_layer (Lifter & lifter, const float pressure[], const float height[], const float temperature[], const float dewpoint[], const float virtemp_arr[], float pcl_vtmpk_arr[], float buoy_arr[], const std::ptrdiff_t N, const float cape_thresh = 100.0, const float cinh_thresh = -250.0, Parcel * mupcl = nullptr)
Computes the Effective Inflow Layer for a given atmospheric sounding.
Author
Kelton Halbert - NWS Storm Prediction Center
Computes the Effective Inflow Layer, or the layer of the atmosphere believed to be the primary source of inflow for supercell thunderstorms. The Effective Inflow Layer, and its use in computing shear and storm relative helicity, is described by Thompson et al. 2007: https://www.spc.noaa.gov/publications/thompson/effective.pdf
Standard/default values for cape_thresh and cinh_thresh have been experimentally determined to be cape_thresh = 100 J/kg and cinh_thresh = -250 J/kg. If a pointer to a parcel object is passed as the last arguments, the most ustanble parcel found during the EIL search will be returned to that pointer.
All arrays are treated as inputs (and expected to be precomputed) except for the buoyancy array. It is more accurately meant to be an empty buffer array that can be used to hold buoyancy values during parcel lifting and integration.
Parameters
lifter (parcel lifting functor)
pressure (Pa)
height (meters)
temperature (K)
dewpoint (K)
virtemp_arr (K)
pcl_vtmpk_arr (K)
buoy_arr (m/s^2)
N (length of arrays)
cape_thresh (J/kg; default=100.0)
cinh_thresh (J/kg; default=-250.0)
mupcl (store the most unstable parcel; defualt=nullptr)
Returns
{bottom, top}
Definition at line 63 of file convective.h.
{
    int eff_kbot = 0;
    float eff_pbot = MISSING;
    float eff_ptop = MISSING;
    float sfc_hght = height[0];
    Parcel maxpcl;
    // search for the effective inflow bottom
    for (std::ptrdiff_t k = 0; k < N; ++k) {
#ifndef NO_QC
        if ((temperature[k] == MISSING) || (dewpoint[k] == MISSING)) {
            continue;
        }
#endif
        Parcel effpcl(pressure[k], temperature[k], dewpoint[k], LPL::MU);
        // We don't want to lift every single profile...
        if (height[k] - sfc_hght > 4000.0) break;
        effpcl.lift_parcel(lifter, pressure, pcl_vtmpk_arr, N);
        buoyancy(pcl_vtmpk_arr, virtemp_arr, buoy_arr, N);
        effpcl.cape_cinh(pressure, height, buoy_arr, N);
        if (effpcl.cape > maxpcl.cape) maxpcl = effpcl;
        if ((effpcl.cape >= cape_thresh) && (effpcl.cinh >= cinh_thresh)) {
            eff_pbot = effpcl.pres;
            eff_kbot = k;
            break;
        }
    }
    if (eff_pbot == MISSING) return {MISSING, MISSING};
    for (std::ptrdiff_t k = eff_kbot + 1; k < N; ++k) {
#ifndef NO_QC
        if ((temperature[k] == MISSING) || (dewpoint[k] == MISSING)) {
            continue;
        }
#endif
        Parcel effpcl(pressure[k], temperature[k], dewpoint[k], LPL::MU);
        effpcl.lift_parcel(lifter, pressure, pcl_vtmpk_arr, N);
        buoyancy(pcl_vtmpk_arr, virtemp_arr, buoy_arr, N);
        effpcl.cape_cinh(pressure, height, buoy_arr, N);
        if (effpcl.cape > maxpcl.cape) maxpcl = effpcl;
        if ((effpcl.cape < cape_thresh) || (effpcl.cinh < cinh_thresh)) {
            eff_ptop = effpcl.pres;
            break;
        }
    }
    if (eff_ptop == MISSING) return {MISSING, MISSING};
    if (mupcl) *mupcl = maxpcl;
    return {eff_pbot, eff_ptop};
}
References buoyancy(), sharp::Parcel::cape, sharp::Parcel::cape_cinh(), sharp::Parcel::cinh, height, sharp::Parcel::lift_parcel(), MISSING, MU, sharp::Parcel::pres, and pressure.
Referenced by sharp_effective_inflow_layer().
effective_inflow_layer() [2/3]
PressureLayer sharp::effective_inflow_layer (sharp::lifter_cm1 & lifter, const float pressure[], const float height[], const float temperature[], const float dewpoint[], const float virtemp_arr[], float pcl_vtmpk_arr[], float buoy_arr[], const std::ptrdiff_t N, const float cape_thresh, const float cinh_thresh, Parcel * mupcl)
effective_inflow_layer() [3/3]
PressureLayer sharp::effective_inflow_layer (sharp::lifter_wobus & lifter, const float pressure[], const float height[], const float temperature[], const float dewpoint[], const float virtemp_arr[], float pcl_vtmpk_arr[], float buoy_arr[], const std::ptrdiff_t N, const float cape_thresh, const float cinh_thresh, Parcel * mupcl)
energy_helicity_index()
float sharp::energy_helicity_index (float cape, float helicity)
Definition at line 223 of file convective.cpp.
{
#ifndef NO_QC
    if ((cape == MISSING) || (helicity == MISSING)) {
        return MISSING;
    }
#endif
    return (cape * helicity) / 160000.0f;
}
References helicity(), and MISSING.
Referenced by sharp_energy_helicity_index().
entrainment_cape()
float sharp::entrainment_cape (const float pressure[], const float height[], const float temperature[], const float mse_arr[], const float u_wind[], const float v_wind[], const std::ptrdiff_t N, Parcel * pcl)
Computes Entrainment CAPE using a previously lifted parcel.
Author
Kelton Halbert - NWS Storm Prediction Center
Computes Entrainment CAPE, or ECAPE, as described by Peters et al. 2023, "An analytic formula for entraining CAPE in mid-latitude storm environments".
Parameters
pressure (Pa)
height (meters)
temperature (degK)
mse_arr ()
u_wind (m/s)
v_wind (m/s)
N (length of arrays)
pcl (Precomputed parcel)
Returns
ECAPE
Definition at line 123 of file convective.cpp.
{
    // if cape is zero, we get a divide by zero issue later.
    // there can "technically" be LFC/EL without CAPE because of very,
    // very shallow buoyancy near zero when searching for LFC/EL.
    // To-Do: maybe refactor LFC/EL search?
    if ((pcl->lfc_pressure == MISSING) || (pcl->lfc_pressure == MISSING) ||
        (pcl->cape == 0)) {
        return 0.0;
    }
    float *mse_diff = new float[N];
    float *mse_bar = new float[N];
    // compute MSE_bar
    mse_bar[0] = mse_arr[0];
    const float psfc = pressure[0];
    for (std::ptrdiff_t k = 1; k < N; ++k) {
        PressureLayer mn_lyr = {psfc, pressure[k]};
        mse_bar[k] = layer_mean(mn_lyr, pressure, mse_arr, N);
    }
    // compute MSE_star
    const float hsfc = height[0];
    for (std::ptrdiff_t k = 0; k < N; ++k) {
        const float tmpk = temperature[k];
        const float rsat = mixratio(pressure[k], tmpk);
        const float qsat = specific_humidity(rsat);
        const float height_agl = height[k] - hsfc;
        const float mse_star = moist_static_energy(height_agl, tmpk, qsat);
        mse_diff[k] = buoyancy_dilution_potential(tmpk, mse_bar[k], mse_star);
    }
    // compute NCAPE
    PressureLayer plyr = {pcl->lfc_pressure, pcl->eql_pressure};
    HeightLayer hlyr = pressure_layer_to_height(plyr, pressure, height, N);
    const float NCAPE = integrate_layer_trapz(hlyr, mse_diff, height, N);
    // Compute the Bunkers non-parcel based storm motion
    WindComponents strm_mtn =
        storm_motion_bunkers(pressure, height, u_wind, v_wind, N, {0.0, 6000.0},
                             {0.0, 6000.0}, false, false);
    // get the mean 0-1km storm relative wind
    HeightLayer layer = {hsfc + 0.0f, hsfc + 1000.0f};
    LayerIndex layer_idx = get_layer_index(layer, height, N);
    // loop from the surface to the last level before 1km AGL.
    float V_sr_mean = 0.0;
    int count = 0;
    for (std::ptrdiff_t k = 0; k < layer_idx.ktop + 1; ++k) {
#ifndef NO_QC
        if ((u_wind[k] == MISSING) || (v_wind[k] == MISSING)) {
            continue;
        }
#endif
        V_sr_mean +=
            vector_magnitude(u_wind[k] - strm_mtn.u, v_wind[k] - strm_mtn.v);
        count += 1;
    }
    const float u_1km = interp_height(layer.top, height, u_wind, N);
    const float v_1km = interp_height(layer.top, height, v_wind, N);
    V_sr_mean += vector_magnitude(u_1km - strm_mtn.u, v_1km - strm_mtn.v);
    V_sr_mean = V_sr_mean / (count + 1);
    // now for all of the ECAPE nonsense
    constexpr float L = 120.0;
    const float H =
        interp_pressure(pcl->eql_pressure, pressure, height, N) - hsfc;
    constexpr float sigma = 1.6;
    constexpr float alpha = 0.8;
    const float pitchfork = (VKSQ * (alpha * alpha) * (PI * PI) * L) /
                            (PRANDTL * (sigma * sigma) * H);
    const float V_sr_tilde = V_sr_mean / std::sqrt(2.0f * pcl->cape);
    const float V_sr_tilde_sq = V_sr_tilde * V_sr_tilde;
    const float N_tilde = NCAPE / pcl->cape;
    const float term1 = pitchfork / V_sr_tilde_sq;
    const float term2 = 1.0f + pitchfork + term1 * N_tilde;
    const float term3 = 4.0f * term1 * (1.0f - pitchfork * N_tilde);
    const float sqrt_term = term2 * term2 + term3;
    // in the case of a negative solution,
    // set ECAPE to 0;
    if (sqrt_term < 0) {
        return 0;
    }
    const float E_tilde = V_sr_tilde_sq + (-1.0f - pitchfork - (term1)*N_tilde +
                                           std::sqrt(sqrt_term)) /
                                              (2.0f * term1);
    delete[] mse_diff;
    delete[] mse_bar;
    return E_tilde * pcl->cape;
}
References buoyancy_dilution_potential(), sharp::Parcel::cape, sharp::Parcel::eql_pressure, get_layer_index(), height, integrate_layer_trapz(), interp_height(), interp_pressure(), sharp::LayerIndex::ktop, layer_mean(), sharp::Parcel::lfc_pressure, MISSING, mixratio(), moist_static_energy(), PI, PRANDTL, pressure, pressure_layer_to_height(), specific_humidity(), storm_motion_bunkers(), sharp::WindComponents::u, sharp::WindComponents::v, vector_magnitude(), and VKSQ.
Referenced by sharp_entrainment_cape().
get_layer_index() [1/3]
LayerIndex sharp::get_layer_index (HeightLayer & layer, const float height[], const std::ptrdiff_t N)
Finds the array indices corresponding to the given sharp::HeightLayer.
Author
Kelton Halbert - NWS Storm Prediction Center
Returns the array indices corresponding to the given sharp::HeightLayer, and performs bounds checking on the layer. As part of the bounds checking, the sharp::HeightLayer is modified if the bottom or top of the layer is out of bounds, which is why it gets passed as a reference.
If the exact values of the top and bottom of the layer are present, their indices are ignored. The default behavior is that the bottom and top of a layer is computed by interpolation by default, since it may or may not be present in the native data.
Parameters
layer {bottom, top}
height (meters)
N (length of array)
Returns
{kbot, ktop}
Definition at line 85 of file layer.cpp.
{
    static constexpr auto bottom_comp = std::less<float>();
    static constexpr auto top_comp = std::greater<float>();
    return get_layer_index(layer, height, N, bottom_comp, top_comp);
}
References get_layer_index(), and height.
get_layer_index() [2/3]
template<typename L , typename Cb , typename Ct > constexpr LayerIndex sharp::get_layer_index (L & layer, const float coord[], const std::ptrdiff_t N, const Cb bottom_comp, const Ct top_comp) constexpr
Returns the array indices corresponding to the given layer.
Author
Kelton Halbert - NWS Storm Prediction Center
This template function encapsulates the algorithm that both bounds checks layer operations and returns the array indices to the corresponding coordinate array, excluding the top and bottom of the layer. Specifically, the LayerIndex is [bottom, top] exclusive, and can be interpreted as the interior range the layer bounds. This behaviour is due to the fact many algorithms used will get the interpolated top and bottom values of the layer, meaning for looping purposes we only want the inner range of indices.
NOTE: If layer.bottom or layer.top are out of bounds, this function will truncate the layer to the coordinate range of data provided by coord[] in an attempt to gracefully continue and produce a result. This will modify the layer and is why it is passed as a reference. If you do not wish to have this behavior, it is up to the user to ensure they assign meaningful values to the layers and not request data out of bounds.
Parameters
layer {bottom, top}
coord (height or pressure)
N (length of array)
bottom_comp (function comparing the layer bottom to coord array)
top_comp (function comparing the layer top to coord array)
Returns
{kbot, ktop}
Definition at line 174 of file layer.h.
{
    // bounds check out search!
    if (bottom_comp(layer.bottom, coord[0])) {
        layer.bottom = coord[0];
    }
    if (top_comp(layer.top, coord[N - 1])) {
        layer.top = coord[N - 1];
    }
    // whether pressure or height coordiantes, the bottom
    // comparitor passed to the function will determine
    // how to search
    std::ptrdiff_t lower_idx = lower_bound(coord, N, layer.bottom, bottom_comp);
    std::ptrdiff_t upper_idx = upper_bound(coord, N, layer.top, bottom_comp);
    // If the layer top is in between two levels, this check ensures
    // that our index is below the top for interpolation reasons
    upper_idx -= ((top_comp(coord[upper_idx], layer.top)) & (upper_idx > 0));
    return {lower_idx, upper_idx};
}
References lower_bound(), and upper_bound().
Referenced by entrainment_cape(), sharp::Parcel::find_lfc_el(), get_layer_index(), helicity(), integrate_layer_trapz(), layer_minmax(), sharp::Parcel::lift_parcel(), sharp::Parcel::most_unstable_parcel(), sharp_get_HeightLayer_index(), and sharp_get_PressureLayer_index().
get_layer_index() [3/3]
LayerIndex sharp::get_layer_index (PressureLayer & layer, const float pressure[], const std::ptrdiff_t N)
Finds the array indices corresponding to the given sharp::PressureLayer.
Author
Kelton Halbert - NWS Storm Prediction Center
Returns the array indices corresponding to the given sharp::PressureLayer, and performs bounds checking on the layer. As part of the bounds checking, the sharp::PressureLayer is modified if the bottom or top of the layer is out of bounds, which is why it gets passed as a reference.
If the exact values of the top and bottom of the layer are present, their indices are ignored. The default behavior is that the bottom and top of a layer is computed by interpolation by default, since it may or may not be present in the native data.
Parameters
layer {bottom, top}
pressure (Pa)
N (length of array)
Returns
{kbot, ktop}
Definition at line 77 of file layer.cpp.
{
    static constexpr auto bottom_comp = std::greater<float>();
    static constexpr auto top_comp = std::less<float>();
    return get_layer_index(layer, pressure, N, bottom_comp, top_comp);
}
References get_layer_index(), and pressure.
height_layer_to_pressure()
PressureLayer sharp::height_layer_to_pressure (HeightLayer layer, const float pressure[], const float height[], const std::ptrdiff_t N, const bool isAGL = false)
Converts a sharp::HeightLayer to a sharp::PressureLayer.
Author
Kelton Halbert - NWS Storm Prediction Center
Converts a sharp::HeightLayer to a sharp::PressureLayer via interpolation, with a flag to signal whether the input layer is in meters AGL or meters MSL. If for some strange reason you provide a HeightLayer that is out of the bounds of height[], then the bottom and top of the output layer will be set to sharp::MISSING.
Parameters
layer (meters)
pressure (Pa)
height (meters)
N (Length of arrays)
isAGL Whether the input layer is AGL / MSL (default: false)
Returns
{bottom, top}
Definition at line 93 of file layer.cpp.
{
    if (isAGL) {
        layer.bottom += height[0];
        layer.top += height[0];
    }
    if ((layer.bottom < height[0]) || (layer.top > height[N - 1])) {
        return {MISSING, MISSING};
    }
    const float pbot = interp_height(layer.bottom, height, pressure, N);
    const float ptop = interp_height(layer.top, height, pressure, N);
    return {pbot, ptop};
}
References sharp::HeightLayer::bottom, height, interp_height(), MISSING, pressure, and sharp::HeightLayer::top.
Referenced by layer_mean(), sharp_HeightLayer_to_PressureLayer(), and storm_motion_bunkers().
helicity()
template<typename L > float sharp::helicity (L layer, WindComponents storm_motion, const float coord[], const float u_wind[], const float v_wind[], const std::ptrdiff_t N)
Computes the Storm Relative Helicity (SRH) over a given layer.
Author
Kelton Halbert - NWS Storm Prediction Center
Computes the Storm Relative Helicity (SRH) over a given layer using storm motion vector components stored in sharp::WindComponents. This tempalte is the generalized form that will fill in the appropriate interpolation calls and coordinate arrays depending on whether a sharp::PressureLayer or sharp::HeightLayer gets passed to this template. The other API instances are just static instantiations of this template.
This integration occurs over the given arrays of coord, u_wind, and v_wind, with N elements in each. The integration only uses interpolation for the top and bottom of the specified layer.
If using a sharp::HeightLayer, units are expected in above-ground-level (AGL), and gets converted to above-mean-sea-level (MSL) during the computation.
Parameters
layer {bottom, top}
storm_motion {storm_u, storm_v}
coord (meters or Pa)
u_wind (m/s)
v_wind (m/s)
N (length of arrays)
Returns
storm_relative_helicity
Definition at line 342 of file winds.h.
{
#ifndef NO_QC
    if ((storm_motion.u == MISSING) || (storm_motion.v == MISSING)) {
        return MISSING;
    }
    if ((layer.bottom == MISSING) || (layer.top == MISSING)) {
        return MISSING;
    }
#endif
    float sru_bot;
    float srv_bot;
    if constexpr (layer.coord == LayerCoordinate::height) {
        // get the height in MSL by adding the surface height
        layer.bottom += coord[0];
        layer.top += coord[0];
        // Get the interpolated bottom of the layer to integrate
        // and convert to storm-relative winds
        sru_bot = interp_height(layer.bottom, coord, u_wind, N);
        srv_bot = interp_height(layer.bottom, coord, v_wind, N);
    } else {
        // Get the interpolated bottom of the layer to integrate
        // and convert to storm-relative winds
        sru_bot = interp_pressure(layer.bottom, coord, u_wind, N);
        srv_bot = interp_pressure(layer.bottom, coord, v_wind, N);
    }
    sru_bot -= storm_motion.u;
    srv_bot -= storm_motion.v;
    // Get the vertical array indices corresponding to our layer,
    // while also bounds checking our search. Indices exclude the
    // top and bottom layers that will be interpolated.
    LayerIndex layer_idx = get_layer_index(layer, coord, N);
    // will get set in first loop iter
    float sru_top;
    float srv_top;
    float layer_helicity = 0.0;
    for (std::ptrdiff_t k = layer_idx.kbot; k <= layer_idx.ktop; ++k) {
#ifndef NO_QC
        if ((u_wind[k] == MISSING) || (v_wind[k] == MISSING)) {
            continue;
        }
#endif
        // top of layer storm relative winds
        sru_top = u_wind[k] - storm_motion.u;
        srv_top = v_wind[k] - storm_motion.v;
        // integrate layer
        layer_helicity += (sru_top * srv_bot) - (sru_bot * srv_top);
        // set the top to be the bottom
        // of the next layer
        sru_bot = sru_top;
        srv_bot = srv_top;
    }
    // Get the interpolated top of the layer to integrate
    // and convert to storm-relative winds
    if constexpr (layer.coord == LayerCoordinate::height) {
        sru_top = interp_height(layer.top, coord, u_wind, N);
        srv_top = interp_height(layer.top, coord, v_wind, N);
    } else {
        sru_top = interp_pressure(layer.top, coord, u_wind, N);
        srv_top = interp_pressure(layer.top, coord, v_wind, N);
    }
    sru_top -= storm_motion.u;
    srv_top -= storm_motion.v;
    // integrate the final layer
    layer_helicity += (sru_top * srv_bot) - (sru_bot * srv_top);
    return layer_helicity;
}
References get_layer_index(), height, interp_height(), interp_pressure(), sharp::LayerIndex::kbot, sharp::LayerIndex::ktop, MISSING, sharp::WindComponents::u, and sharp::WindComponents::v.
Referenced by energy_helicity_index(), sharp_HeightLayer_helicity(), and sharp_PressureLayer_helicity().
integrate_layer_trapz()
template<typename L > float sharp::integrate_layer_trapz (L layer, const float var_array[], const float coord_array[], const std::ptrdiff_t N, const int integ_sign = 0, const bool weighted = false)
Returns a trapezoidal integration of the given layer.
Author
Kelton Halbert - NWS Storm Prediction Center
Returns a trapezoidal integration of the given data array over the given sharp::PressureLayer or sharp::HeightLayer. There is an additional default argument that determines whether this is a weighted average or not. The sign of the integration may be passed as well, i.e. integrating only positive or negative values, by passing a 1 or -1 to integ_sign.
Parameters
layer (sharp::PressureLayer or sharp::HeightLayer)
var_array (data array to integrate)
coord_array (coordinate array to integrate over)
N (length of arrays)
weighted (bool; default=false)
integ_sign (int; default=0)
Returns
integrated_value
Definition at line 455 of file layer.h.
{
    float var_lyr_bottom;
    float coord_lyr_bottom = layer.bottom;
    float var_lyr_top;
    float coord_lyr_top = layer.top;
    float integrated = 0.0;
    float weights = 0.0;
    const bool isign = std::signbit(integ_sign);
    // using constexpr means that this if statement optimizes
    // away at compile time since the layer coordinate is known
    LayerIndex idx = get_layer_index(layer, coord_array, N);
    if constexpr (layer.coord == LayerCoordinate::height) {
        var_lyr_bottom = interp_height(layer.bottom, coord_array, var_array, N);
        var_lyr_top = interp_height(layer.top, coord_array, var_array, N);
    } else {
        var_lyr_bottom =
            interp_pressure(layer.bottom, coord_array, var_array, N);
        var_lyr_top = interp_pressure(layer.top, coord_array, var_array, N);
    }
    for (std::ptrdiff_t k = idx.kbot; k < idx.ktop; ++k) {
#ifndef NO_QC
        if (var_array[k] == MISSING) {
            continue;
        }
#endif
        float coord_bottom = coord_array[k];
        float var_bottom = var_array[k];
        float coord_top = coord_array[k + 1];
        float var_top = var_array[k + 1];
        float layer_avg = _integ_trapz(var_top, var_bottom, coord_top,
                                       coord_bottom, weights, weighted);
        float cond =
            (float)((!integ_sign) | (isign == std::signbit(layer_avg)));
        integrated += cond * layer_avg;
    }
    // interpolated bottom of layer
    float layer_avg =
        _integ_trapz(var_array[idx.kbot], var_lyr_bottom, coord_array[idx.kbot],
                     coord_lyr_bottom, weights, weighted);
    float cond = ((!integ_sign) | (isign == std::signbit(layer_avg)));
    integrated += cond * layer_avg;
    // interpolated top of layer
    layer_avg = _integ_trapz(var_lyr_top, var_array[idx.ktop], coord_lyr_top,
                             coord_array[idx.ktop], weights, weighted);
    cond = ((!integ_sign) | (isign == std::signbit(layer_avg)));
    integrated += cond * layer_avg;
    if constexpr (layer.coord == LayerCoordinate::pressure) {
        integrated *= -1.0f;
        weights *= -1.0f;
    }
    if (weighted) integrated /= weights;
    return integrated;
}
References _integ_trapz(), get_layer_index(), height, interp_height(), interp_pressure(), sharp::LayerIndex::kbot, sharp::LayerIndex::ktop, MISSING, and pressure.
Referenced by sharp::Parcel::cape_cinh(), entrainment_cape(), layer_mean(), sharp_HeightLayer_integrate(), and sharp_PressureLayer_integrate().
interp_height()
float sharp::interp_height (const float height_val, const float height_arr[], const float data_arr[], const std::ptrdiff_t N)
Linearly interpolate a data field to a requested height level.
Author
Kelton Halbert - NWS Storm Prediction Center
Interpolates data in height coordinates (meters) when given the array of heights, the array of data to interpolate, a height level to interpolate to, and the number of levels in the arrays.
The height array must be sorted in ascending order and monotonic. For performance reasons, this routine assumes your data is well ordered. If weird stuff happens, check the ordering of your array values first.Duplicate height values or decreasing height values may produce unexpected results.
Parameters
height_val The height value to interpolate data to
height_arr The array of height values in the profile
data_arr The array of data values you want interpolated
N The the array length (number of elements)
Returns
The value of data_arr at the requested height_val.
Definition at line 23 of file interp.cpp.
{
#ifndef NO_QC
    if (height_val == MISSING) return MISSING;
    if (std::isnan(height_val)) return MISSING;
    // If the height value is beyond the top of the profile,
    // or below the surface, we can't reasonably extrapolate
    if ((height_val > height_arr[N - 1]) || (height_val < height_arr[0]))
        return MISSING;
#endif
    static constexpr auto comp = std::less<float>();
    std::ptrdiff_t idx_top = upper_bound(height_arr, N, height_val, comp);
    std::ptrdiff_t idx_bot = idx_top - 1;
#ifndef NO_QC
    for (; idx_bot > 0; --idx_bot) {
        if (data_arr[idx_bot] != MISSING) break;
    }
    for (; idx_top < N; ++idx_top) {
        if (data_arr[idx_top] != MISSING) break;
    }
    // in the case the data are still missing at this point,
    // return a missing value
    if ((data_arr[idx_bot] == MISSING) || (data_arr[idx_top] == MISSING))
        return MISSING;
#endif
    const float height_bot = height_arr[idx_bot];
    const float height_top = height_arr[idx_top];
    const float data_bot = data_arr[idx_bot];
    const float data_top = data_arr[idx_top];
    // normalize the distance between values
    // to a range of 0-1 for the lerp routine
    const float dz_norm = (height_val - height_bot) / (height_top - height_bot);
    // return the linear interpolation
    return lerp(data_bot, data_top, dz_norm);
}
References lerp(), MISSING, and upper_bound().
Referenced by entrainment_cape(), height_layer_to_pressure(), helicity(), integrate_layer_trapz(), lapse_rate(), layer_minmax(), sharp::Parcel::mixed_layer_parcel(), sharp_interp_height(), and wind_shear().
interp_pressure()
float sharp::interp_pressure (const float pressure_val, const float pressure_arr[], const float data_arr[], const std::ptrdiff_t N)
Linearly interpolate a data field to a requested pressure level.
Author
Kelton Halbert - NWS Storm Prediction Center
Interpolates data in pressure coordinates (mb) when given the array of pressure values, the array of data to interpolate, a pressure level to interpolate to, and the number of levels in the arrays.
The pressure array must be sorted in descending order and monotonic. Duplicate pressure values or increasing pressure values may produce unexpected results.
Parameters
pressure_val The pressure value to interpolate data to
pressure_arr The array of pressure values in the profile
data_arr The array of data values you want interpolated
N The the array length (number of elements)
Returns
The value of data_arr at the requested pressure_val.
Definition at line 66 of file interp.cpp.
{
#ifndef NO_QC
    if (pressure_val == MISSING) return MISSING;
    if (std::isnan(pressure_val)) return MISSING;
    // If the pressure value is beyond the top of the profile,
    // or below the surface, we can't reasonably extrapolate
    if ((pressure_val < pressure_arr[N - 1]) ||
        (pressure_val > pressure_arr[0])) {
        return MISSING;
    }
#endif
    static constexpr auto comp = std::greater<float>();
    std::ptrdiff_t idx_top = upper_bound(pressure_arr, N, pressure_val, comp);
    std::ptrdiff_t idx_bot = idx_top - 1;
#ifndef NO_QC
    for (; idx_bot > 0; --idx_bot) {
        if (data_arr[idx_bot] != MISSING) break;
    }
    for (; idx_top < N; ++idx_top) {
        if (data_arr[idx_top] != MISSING) break;
    }
    // in the case the data are still missing at this point,
    // return a missing value
    if ((data_arr[idx_bot] == MISSING) || (data_arr[idx_top] == MISSING))
        return MISSING;
#endif
    const float pressure_bot = pressure_arr[idx_bot];
    const float pressure_top = pressure_arr[idx_top];
    const float data_bot = data_arr[idx_bot];
    const float data_top = data_arr[idx_top];
    // In order to linearly interpolate pressure properly, distance needs
    // to be calculated in log10(pressure) coordinates and normalized
    // between 0 and 1 for the lerp routine.
    const float dp_norm =
        (std::log10(pressure_bot) - std::log10(pressure_val)) /
        (std::log10(pressure_bot) - std::log10(pressure_top));
    // return the linear interpolation
    return lerp(data_bot, data_top, dp_norm);
}
References lerp(), MISSING, and upper_bound().
Referenced by entrainment_cape(), sharp::Parcel::find_lfc_el(), helicity(), integrate_layer_trapz(), layer_minmax(), mean_wind(), pressure_layer_to_height(), sharp_interp_pressure(), storm_motion_bunkers(), and wind_shear().
lapse_rate() [1/2]
float sharp::lapse_rate (HeightLayer layer_agl, const float height[], const float temperature[], const std::ptrdiff_t N)
compute the lapse rate over the given sharp::HeightLayer (AGL)
Author
Kelton Halbert - NWS Storm Prediction Center
Computes the lapse rate over a given sharp::HeightLayer above-ground-level. This routine handles converting AGL to MSL by adding the surface height value to the layer.
Parameters
layer_agl (meters AGL)
height (meters MSL)
temperature (K)
N (length of arrays)
Returns
Temperature Lapse Rate (K/km)
Definition at line 410 of file thermo.cpp.
{
#ifndef NO_QC
    if ((layer_agl.bottom == MISSING) || (layer_agl.top == MISSING)) {
        return MISSING;
    }
#endif
    // convert from agl to msl
    layer_agl.bottom += height[0];
    layer_agl.top += height[0];
    // bounds check the height layer
    if (layer_agl.bottom < height[0]) {
        layer_agl.bottom = height[0];
    }
    if (layer_agl.top > height[N - 1]) {
        layer_agl.top = height[N - 1];
    }
    // lower and upper temperature
    const float tmpc_l =
        interp_height(layer_agl.bottom, height, temperature, N);
    const float tmpc_u = interp_height(layer_agl.top, height, temperature, N);
#ifndef NO_QC
    if ((tmpc_l == MISSING) || (tmpc_u == MISSING)) {
        return MISSING;
    }
#endif
    // dT/dz, positive (definition of lapse rate), in km
    const float dz = layer_agl.top - layer_agl.bottom;
    return ((tmpc_u - tmpc_l) / dz) * -1000.0f;
}
References sharp::HeightLayer::bottom, height, interp_height(), MISSING, and sharp::HeightLayer::top.
Referenced by lapse_rate(), lapse_rate_max(), sharp_HeightLayer_lapse_rate(), and sharp_PressureLayer_lapse_rate().
lapse_rate() [2/2]
float sharp::lapse_rate (PressureLayer layer, const float pressure[], const float height[], const float temperature[], const std::ptrdiff_t N)
compute the lapse rate over the given sharp::PressureLayer
Author
Kelton Halbert - NWS Storm Prediction Center
Computes the lapse rate over a given sharp::PressureLayer. This routine handles converting the pressure layer into a height layer, and then calles the sharp::HeightLayer implementation of this routine.
Parameters
layer (Pa)
pressure (Pa)
height (meters MSL)
temperature (K)
N (length of arrays)
Returns
Temperature Lapse Rate (K/km)
Definition at line 445 of file thermo.cpp.
{
#ifndef NO_QC
    if ((layer.bottom == MISSING) || (layer.top == MISSING)) {
        return MISSING;
    }
#endif
    // bounds check the pressure layer
    if (layer.bottom > pressure[0]) {
        layer.bottom = pressure[0];
    }
    if (layer.top < pressure[N - 1]) {
        layer.top = pressure[N - 1];
    }
    HeightLayer h_layer =
        pressure_layer_to_height(layer, pressure, height, N, true);
    return lapse_rate(h_layer, height, temperature, N);
}
References sharp::PressureLayer::bottom, height, lapse_rate(), MISSING, pressure, pressure_layer_to_height(), and sharp::PressureLayer::top.
lapse_rate_max() [1/2]
float sharp::lapse_rate_max (HeightLayer layer_agl, const float depth, const float height[], const float temperature[], const std::ptrdiff_t N, HeightLayer * max_lyr = nullptr)
Find the maximum lapse rate within a specified layer/depth (AGL).
Author
Kelton Halbert - NWS Storm Prediction Center
Given a layer of the atmosphere (e.g. 2 - 6 km), find the maximum lapse rate over the provided depth (e.g. 2 km) within that given layer. Returns the maximum lapse rate, with the optional ability to return the layer that lapse rate exists within.
Parameters
layer_agl (meters AGL)
depth (meters)
height (meters MSL)
temperature (K)
N (length of arrays)
max_lyr (The sharp::HeightLayer of the max lapse rate)
Returns
Maximum Temperature Lapse Rate (K/km)
Definition at line 468 of file thermo.cpp.
{
    float max_lr = MISSING;
    for (float z = layer_agl.bottom; z <= (layer_agl.top - depth);
         z += layer_agl.delta) {
        HeightLayer lyr = {z, z + depth};
        float lr = lapse_rate(lyr, height, temperature, N);
        if (lr > max_lr) {
            max_lr = lr;
            if (max_lyr) {
                max_lyr->bottom = lyr.bottom;
                max_lyr->top = lyr.top;
            }
        }
    }
    return max_lr;
}
References sharp::HeightLayer::bottom, sharp::HeightLayer::delta, height, lapse_rate(), MISSING, and sharp::HeightLayer::top.
lapse_rate_max() [2/2]
float sharp::lapse_rate_max (PressureLayer layer, const float depth, const float pressure[], const float height[], const float temperature[], const std::ptrdiff_t N, PressureLayer * max_lyr = nullptr)
Find the maximum lapse rate within a specified layer/depth (Pres)
Author
Kelton Halbert - NWS Storm Prediction Center
Given a mayer of the atmisphere (e.g. 800 hPa - 500 hPa), find the maximum lapse rate over the provided depth (e.g. 100 hPa) within that given layer. Returns the maximum lapse rate, with the optional ability to return the layer that lapse rate exists within.
Parameters
layer (Pa)
depth (Pa)
pressure (Pa)
height (meters MSL)
temperature (K)
N (length of arrays)
max_lyr (The sharp::PressureLayer of the max lapse rate)
Returns
Maximum Temperature Lapse Rate (K/km)
Definition at line 487 of file thermo.cpp.
{
    float max_lr = MISSING;
    for (float p = layer.bottom; p >= (layer.top + depth); p += layer.delta) {
        PressureLayer lyr = {p, p - depth};
        float lr = lapse_rate(lyr, pressure, height, temperature, N);
        if (lr > max_lr) {
            max_lr = lr;
            if (max_lyr) {
                max_lyr->bottom = lyr.bottom;
                max_lyr->top = lyr.top;
            }
        }
    }
    return max_lr;
}
References sharp::PressureLayer::bottom, sharp::PressureLayer::delta, height, lapse_rate(), MISSING, pressure, and sharp::PressureLayer::top.
layer_max()
template<typename L > constexpr float sharp::layer_max (L layer, const float coord_arr[], const float data_arr[], const std::ptrdiff_t N, float * lvl_of_max = nullptr) constexpr
Returns the maximim value in the given layer.
Author
Kelton Halbert - NWS Storm Prediction Center
Returns the maximum value observed within the given data array over the given sharp::PressureLayer or sharp::HeightLayer. The function bounds checks the layer by calling sharp::get_layer_index.
If lvl_of_max is not a nullptr, then the pointer will be dereferenced and filled with the coordinate of the maximum value.
Parameters
layer (sharp::PressureLayer or sharp::HeightLayer)
coord_arr (coordinate units; Pa or meters)
data_arr (data array to find max on)
N (length of arrays)
lvl_of_max (level of max val)
Returns
layer_max
Definition at line 426 of file layer.h.
{
    constexpr auto comp = std::greater<float>();
    return layer_minmax(layer, coord_arr, data_arr, N, lvl_of_max, comp);
}
References layer_minmax().
Referenced by sharp_HeightLayer_max(), and sharp_PressureLayer_max().
layer_mean() [1/2]
float sharp::layer_mean (HeightLayer layer, const float height[], const float pressure[], const float data_arr[], const std::ptrdiff_t N, const bool isAGL = false)
Computes the mass-weighted mean value of a field over a given height layer.
Author
Kelton Halbert - NWS Storm Prediction Center
Computes the mass-weighted mean value of given arrays of data and corresponding height coordinates over the given sharp::HeightLayer. This is really just a fancy wrapper around the implementation that uses sharp::PressureLayer.
Parameters
layer (sharp::HeightLayer)
height (vertical height array; meters)
pressure (vertical pressure array; Pa)
data_arr (The data for which to compute a mean)
N (length of pressure and data arrays)
isAGL (whether or not intput is in AGL or MSL)
Returns
layer_mean
Definition at line 151 of file layer.cpp.
{
#ifndef NO_QC
    if ((layer.bottom == MISSING) || (layer.top == MISSING)) {
        return MISSING;
    }
#endif
    if (isAGL) {
        layer.bottom += height[0];
        layer.top += height[0];
    }
    if (layer.bottom < height[0]) {
        layer.bottom = height[0];
    }
    if (layer.top > height[N - 1]) {
        layer.top = height[N - 1];
    }
    PressureLayer pres_layer =
        height_layer_to_pressure(layer, pressure, height, N, false);
    return integrate_layer_trapz(pres_layer, data_arr, pressure, N, 0, true);
}
References sharp::HeightLayer::bottom, height, height_layer_to_pressure(), integrate_layer_trapz(), MISSING, pressure, and sharp::HeightLayer::top.
layer_mean() [2/2]
float sharp::layer_mean (PressureLayer layer, const float pressure[], const float data_arr[], const std::ptrdiff_t N)
Computes the mass-weighted mean value of a field over a given pressure layer.
Author
Kelton Halbert - NWS Storm Prediction Center
Computes the mass-weighted mean value of given arrays of data and corresponding pressure coordinates over the given sharp::PressureLayer.
Parameters
layer (sharp::PressureLayer)
pressure (vertical pressure array; Pa)
data_arr (The data for which to compute a mean)
N (length of pressure and data arrays)
Returns
layer_mean
Definition at line 132 of file layer.cpp.
{
#ifndef NO_QC
    if ((layer.bottom == MISSING) || (layer.top == MISSING)) {
        return MISSING;
    }
#endif
    if (layer.bottom > pressure[0]) {
        layer.bottom = pressure[0];
    }
    if (layer.top < pressure[N - 1]) {
        layer.top = pressure[N - 1];
    }
    return integrate_layer_trapz(layer, data_arr, pressure, N, 0, true);
}
References sharp::PressureLayer::bottom, integrate_layer_trapz(), MISSING, pressure, and sharp::PressureLayer::top.
Referenced by entrainment_cape(), sharp::Parcel::mixed_layer_parcel(), sharp_HeightLayer_mean(), and sharp_PressureLayer_mean().
layer_min()
template<typename L > constexpr float sharp::layer_min (L layer, const float coord_arr[], const float data_arr[], const std::ptrdiff_t N, float * lvl_of_min = nullptr) constexpr
Returns the minimum value in the given layer.
Author
Kelton Halbert - NWS Storm Prediction Center
Returns the minimum value observed within the given data array over the given sharp::PressureLayer or sharp::HeightLayer. The function bounds checks the layer by calling sharp::get_layer_index.
If lvl_of_min is not a nullptr, then the pointer will be dereferenced and filled with the coordinate of the minimum value.
Parameters
layer (sharp::PressureLayer or sharp::HeightLayer)
coord_arr (coordinate units; Pa or meters)
data_arr (data array to find min on)
N (length of arrays)
lvl_of_min (level of min val)
Returns
layer_min
Definition at line 396 of file layer.h.
{
    constexpr auto comp = std::less<float>();
    return layer_minmax(layer, coord_arr, data_arr, N, lvl_of_min, comp);
}
References layer_minmax().
Referenced by sharp_HeightLayer_min(), and sharp_PressureLayer_min().
layer_minmax()
template<typename L , typename C > constexpr float sharp::layer_minmax (L layer, const float coord_arr[], const float data_arr[], const std::ptrdiff_t N, float * lvl_min_or_max, const C comp) constexpr
Template for min/max value over sharp::PressureLayer or sharp::HeightLayer.
Author
Kelton Halbert - NWS Storm Prediction Center
This tempalte function contains the algorithm for searching for either the minimum or maximum value over a given sharp::PressureLayer or sharp::HeightLayer. This function is wrapped by the sharp::min_value and sharp::max_value functions, which pass the appropriate comparitor to the template.
If lvl_min_or_max is not a nullptr, then the pointer will be dereferenced and filled with the pressure or height of the maximum/minum value.
Parameters
layer (sharp::PressureLayer or sharp::HeightLayer)
coord_arr (pressure or height)
data_arr (data array to find max on)
N (length of arrays)
lvl_min_or_max (level of min/max val)
comp Comparitor (i.e. std::less or std::greater)
Returns
minmax_value
Definition at line 331 of file layer.h.
{
#ifndef NO_QC
    if ((layer.bottom == MISSING) || (layer.top == MISSING)) {
        return MISSING;
    }
#endif
    LayerIndex layer_idx = get_layer_index(layer, coord_arr, N);
    float min_or_max = MISSING;
    float top_val = MISSING;
    if constexpr (layer.coord == LayerCoordinate::pressure) {
        min_or_max = interp_pressure(layer.bottom, coord_arr, data_arr, N);
        top_val = interp_pressure(layer.top, coord_arr, data_arr, N);
    } else {
        min_or_max = interp_height(layer.bottom, coord_arr, data_arr, N);
        top_val = interp_height(layer.top, coord_arr, data_arr, N);
    }
    float coord_lvl = layer.bottom;
    for (std::ptrdiff_t k = layer_idx.kbot; k < layer_idx.ktop + 1; ++k) {
        const float val = data_arr[k];
        if (comp(val, min_or_max)) {
            min_or_max = val;
            coord_lvl = coord_arr[k];
        }
    }
    if (comp(top_val, min_or_max)) {
        min_or_max = top_val;
        coord_lvl = layer.top;
    }
    if (lvl_min_or_max) *lvl_min_or_max = coord_lvl;
    return min_or_max;
}
References get_layer_index(), interp_height(), interp_pressure(), sharp::LayerIndex::kbot, sharp::LayerIndex::ktop, MISSING, and pressure.
Referenced by layer_max(), and layer_min().
lcl_temperature()
float sharp::lcl_temperature (float temperature, float dewpoint)
Compute the temperature of the LCL.
Author
Kelton Halbert - NWS Storm Prediction Center
Computes the temperature of a parcels LCL in degres Kelvin given the parcel temperature and dewpoint in Kelvin.
This is implemented as in Bolton (1980) eq 15, and is considered to be within a 10th of a degree of the more exact iterative formula.
Parameters
temperature (K)
dewpoint (K)
Returns
lcl_temperature (K)
Definition at line 73 of file thermo.cpp.
{
#ifndef NO_QC
    if ((temperature == MISSING) || (dewpoint == MISSING)) {
        return MISSING;
    }
#endif
    static constexpr float c1 = 56.0f;
    static constexpr float c2 = 800.0f;
    const float term_1 = 1.0 / (dewpoint - c1);
    const float term_2 = std::log(temperature / dewpoint) / c2;
    return (1.0 / (term_1 + term_2)) + c1;
}
References MISSING.
Referenced by drylift(), and sharp_lcl_temperature().
lerp()
constexpr float sharp::lerp (const float __a, const float __b, const float __t) constexpr
Linearly interpolates between a and b with distance t.
Author
C++20 Standard Template Library
This routine was copied from the C++20 standard template library. It is used to linearly interpolate between A and B over a normalized distance T, where 0 <= T <= 1. Full documentation and details can be found in the paper located here: https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0811r3.html
This linear interpolation guarantees the following:
Exactness: lerp(a,b,0)==a & lerp(a,b,1)==b
Monotonicity: cmp(lerp(a,b,t2), lerp(a,b,t1)) * cmp(t2, t1)
cmp(b,a) >= 0, where cmp is an arithmetic three-way comparison function
Determinacy: result of NaN only for lerp(a,a,INFINITY)
Boundedness: t<0 || t>1 || isfinite(lerp(a,b,t))
Consistency: lerp(a,a,t) == a
Parameters
__a left value
__b right value
__t where 0 <= __t <= 1.0
Returns
The value between __a and __b at distance __t between them.
Definition at line 93 of file interp.h.
{
    return __lerp(__a, __b, __t);
}
References __lerp().
Referenced by interp_height(), and interp_pressure().
lower_bound()
template<typename T , typename C = std::less<>> constexpr std::ptrdiff_t sharp::lower_bound (const T array[], const std::ptrdiff_t N, const T value, const C cmp = C{}) constexpr
Finds the index of the lower bound that does not satisfy element < value.
Author
Kelton Halbert - NWS Storm Prediction Center
Based on std::lower_bound, this iterates over an array using a binary search to find the first element that does not satisfy the comparison condition. By default, the comparison is std::less. Binary search expects data to be sorted in ascending order – for pressure level data, change the comparitor.
We use a custom implementation of sharp::lower_bound rather than std::lower_bound for a few reasons. First, we prefer raw pointer arrays over vectors for easy integration with SWIG bindings, C code, and the potential future in which this runs on CUDA architecture. Currently, the algorithms in the STL library are not supported by the CUDA STL, but the types in <functional> (i.e. std::less) are supported by the CUDA STL. Additionally, this implementation of lower_bound is designed to reduce branching.
Parameters
array The array to search over
N The length of the array
value The value for lower-bound comparison
cmp The comparitor
Returns
Index of lower bound
Definition at line 50 of file algorithms.h.
                                                                  {}) {
    std::ptrdiff_t len = N;
    std::ptrdiff_t idx = 0;
    while (len > 1) {
        std::ptrdiff_t half = len / 2;
        idx += cmp(array[idx + half - 1], value) * half;
        len -= half;  // = ceil(len / 2)
    }
    return idx;
}
Referenced by get_layer_index().
mean_wind()
WindComponents sharp::mean_wind (PressureLayer layer, const float pres[], const float u_wind[], const float v_wind[], const std::ptrdiff_t N, const bool weighted)
Compute the mean wind over the given sharp::PressureLayer.
Author
Kelton Halbert - NWS Storm Prediction Center
Computes the mean wind over the given sharp::PressureLayer and arrays of pressure and wind components with a length of N.
Parameters
layer {bottom, top}
pres (Pa)
u_wind (m/s)
v_wind (m/s)
N (length of arrays)
weighted (whether to weight by pressure level)
Returns
{mean_u, mean_v}
Definition at line 104 of file winds.cpp.
{
#ifndef NO_QC
    if ((layer.bottom == MISSING) || (layer.top == MISSING))
        return {MISSING, MISSING};
#endif
    if (layer.bottom > pressure[0]) layer.bottom = pressure[0];
    if (layer.top < pressure[N - 1]) layer.top = pressure[N - 1];
    float pr_lvl = layer.bottom;
    float u_sum = 0;
    float v_sum = 0;
    float weight = 0;
    while (pr_lvl >= layer.top) {
        float w = (weighted) ? pr_lvl : 1.0f;
        u_sum += interp_pressure(pr_lvl, pressure, u_wind, N) * w;
        v_sum += interp_pressure(pr_lvl, pressure, v_wind, N) * w;
        weight += w;
        pr_lvl += layer.delta;
    }
    const float mean_u = u_sum / weight;
    const float mean_v = v_sum / weight;
    return {mean_u, mean_v};
}
References sharp::PressureLayer::bottom, sharp::PressureLayer::delta, interp_pressure(), MISSING, pressure, and sharp::PressureLayer::top.
Referenced by sharp_mean_wind(), and storm_motion_bunkers().
mixratio() [1/2]
float sharp::mixratio (float pressure, float temperature)
Compute the water vapor mixing ratio.
Author
Kelton Halbert - NWS Storm Prediction Center
Returns the water vapor mixing ratio in kg/kg given the environmental pressure in Pascals (Pa) and a temperature (dry-bulb or dewpoint) in Kelvin.
This is computed by calling sharp::vapor_pressure, which uses the Bolton (1980) equations.
Parameters
pressure (Pa)
temperature (K)
Returns
mixratio (kg/kg)
Definition at line 129 of file thermo.cpp.
{
#ifndef NO_QC
    if ((temperature == MISSING) || (pressure == MISSING)) {
        return MISSING;
    }
#endif
    const float e = vapor_pressure(pressure, temperature);
    return (EPSILON * e) / (pressure - e);
}
References EPSILON, MISSING, pressure, and vapor_pressure().
mixratio() [2/2]
float sharp::mixratio (float q)
Compute the water vapor mixing ratio from specific humidity.
Author
Kelton Halbert - NWS Storm Prediction Center
Returns the water vapor mixing ratio in kg/kg given the specific humidity in kg/kg.
Parameters
q (kg/kg)
Returns
mixratio (kg/kg)
Definition at line 122 of file thermo.cpp.
{
#ifndef NO_QC
    if (q == MISSING) return MISSING;
#endif
    return q / (1.0 - q);
}
References MISSING.
Referenced by _solve_cm1(), entrainment_cape(), sharp::Parcel::lift_parcel(), sharp::lifter_wobus::parcel_virtual_temperature(), sharp::lifter_cm1::setup(), sharp_mixratio(), and thetae().
mixratio_ice()
float sharp::mixratio_ice (float pressure, float temperature)
Compute the ice water mixing ratio.
Author
Kelton Halbert - NWS Storm Prediction Center
Returns the ice water mixing ratio in kg/kg given the environmental pressure in Pascals (Pa) and a temperature (dry-bulb or dewpoint) in Kelvin.
This is computed by calling sharp::vapor_pressure_ice, which uses the Bolton (1980) equations.
Parameters
pressure (Pa)
temperature (K)
Returns
mixratio (kg/kg)
Definition at line 140 of file thermo.cpp.
{
#ifndef NO_QC
    if ((temperature == MISSING) || (pressure == MISSING)) {
        return MISSING;
    }
#endif
    const float e = vapor_pressure_ice(pressure, temperature);
    return (EPSILON * e) / (pressure - e);
}
References EPSILON, MISSING, pressure, and vapor_pressure_ice().
Referenced by _solve_cm1(), and sharp_mixratio_ice().
moist_adiabat_cm1()
float sharp::moist_adiabat_cm1 (float pressure, float temperature, float new_pressure, float & rv_total, float & rv, float & rl, float & ri, float pres_incr, float converge, adiabat ma_type)
Compute the temperature of a parcel lifted moist adiabatically to a new level.
Author
Kelton Halbert - NWS Storm Prediction Center
With a given parcel defined by a pressure and temperature (in Pascals and Kelvin), lift it moist adiabatically to a new pressure level (in Pascals) and return the temperature of the parcel at that level.
This function is based on/ripped from George Byran's (NCAR) routine in CM1. It has several options for convergence criteria, pressure increments, and the type of moist adiabat/assumptions (i.e. pseudoadiabatic, adiabatic, liquid, liquid+ice). The sharp::adiabat defines the types of adiabats, and the float references to qv, ql, and qi are used to keep budgets of the moisture variables.
NOTE: rv_total should most likely be the water vapor mixing ratio either at the parcel's sharp::LPL, or the water vapor mixing ratio at the LCL (these are going to be the same value). Essentially, the total water vapor before condensation.
Parameters
pressure (Pa)
temperature (K)
new_pressure (Pa)
rv_total (kg/kg)
rv (kg/kg)
rl (kg/kg)
ri (kg/kg)
pres_incr (Pa)
converge (precision)
ma_type (sharp::adiabat)
Returns
pcl_temperature (K)
Definition at line 288 of file thermo.cpp.
{
#ifndef NO_QC
    if ((temperature == MISSING) || (pressure == MISSING) ||
        (new_pressure == MISSING)) {
        return MISSING;
    }
#endif
    // set up solver variables
    const bool ice = (ma_type >= adiabat::pseudo_ice) ? true : false;
    float dp = new_pressure - pressure;
    const bool ascending = std::signbit(dp);
    const int n_iters =
        (std::abs(dp) < pres_incr) ? 1 : 1 + (int)(std::abs(dp) / pres_incr);
    dp = (n_iters == 1) ? dp : dp / (float)n_iters;
    // Start by setting the "top" variables.
    float pcl_theta_next = theta(pressure, temperature);
    float pcl_pres_next = pressure;
    float pcl_pi_next = std::pow(pressure / THETA_REF_PRESSURE, ROCP);
    float pcl_t_next = pcl_theta_next * pcl_pi_next;
    float pcl_rv_next = rv;
    float pcl_rl_next = rl;
    float pcl_ri_next = ri;
    // Iterate the required number of times to reach the new pressure
    // level from the old one in increments of dp
    for (int i = 0; i < n_iters; ++i) {
        float pcl_theta_prev = pcl_theta_next;
        float pcl_pres_prev = pcl_pres_next;
        float pcl_rv_prev = pcl_rv_next;
        float pcl_rl_prev = pcl_rl_next;
        float pcl_ri_prev = pcl_ri_next;
        float pcl_t_prev = pcl_t_next;
        pcl_pres_next += dp;
        pcl_pi_next = std::pow(pcl_pres_next / THETA_REF_PRESSURE, ROCP);
        // call the iterative solver to get the new parcel
        // theta accounting for liquid (and ice if enabled)
        pcl_theta_next = _solve_cm1(
            pcl_pres_next, pcl_pi_next, pcl_t_next, pcl_rv_next, pcl_rl_next,
            pcl_ri_next, pcl_pres_prev, pcl_t_prev, pcl_theta_prev, pcl_rv_prev,
            pcl_rl_prev, pcl_ri_prev, rv_total, ascending, ice, converge);
        /*printf("%f %f\t%f\t%f %f\n", pcl_pres_prev, pcl_theta_prev,*/
        /*       pcl_pres_next, pcl_rv_next, rv_total);*/
        if ((ma_type == adiabat::pseudo_liq) ||
            (ma_type == adiabat::pseudo_ice)) {
            rv_total = pcl_rv_next;
            pcl_rl_next = 0.0f;
            pcl_ri_next = 0.0f;
        }
    }
    pcl_t_next = pcl_theta_next * pcl_pi_next;
    rv = pcl_rv_next;
    rl = pcl_rl_next;
    ri = pcl_ri_next;
    return pcl_t_next;
}
References _solve_cm1(), MISSING, pressure, pseudo_ice, pseudo_liq, ROCP, theta(), and THETA_REF_PRESSURE.
Referenced by sharp::lifter_cm1::operator()(), and sharp_moist_adiabat_cm1().
moist_static_energy()
float sharp::moist_static_energy (float height_agl, float temperature, float specific_humidity)
Compute moist static energy.
Author
Kelton Halbert - NWS Storm Prediction Center
Parameters
height_agl (meters)
temperature (K)
specific_humidity (kg/kg)
Returns
moist static energy ()
Definition at line 517 of file thermo.cpp.
{
#ifndef NO_QC
    if ((height_agl == MISSING) || (temperature == MISSING) ||
        (specific_humidity == MISSING)) {
        return MISSING;
    }
#endif
    return (CP_DRYAIR * temperature) + (EXP_LV * specific_humidity) +
           (GRAVITY * height_agl);
}
References CP_DRYAIR, EXP_LV, GRAVITY, MISSING, and specific_humidity().
Referenced by entrainment_cape(), and sharp_moist_static_energy().
pressure_layer_to_height()
HeightLayer sharp::pressure_layer_to_height (PressureLayer layer, const float pressure[], const float height[], const std::ptrdiff_t N, const bool toAGL = false)
Converts a sharp::PressureLayer to a sharp::HeightLayer.
Author
Kelton Halbert - NWS Storm Prediction Center
Converts a sharp::PressureLayer to a sharp::HeightLayer via interpolation, with the option of returning the layer in meters AGL or MSL. If for some strange reason you provide a PressureLayer that is out of the bounds of pressure[], then the bottom and top of the output layer will be set to sharp::MISSING.
Parameters
layer (Pa)
pressure (Pa)
height (meters)
N (Length of arrays)
toAGL Flag whether to return meters AGL or MSL (default: false)
Returns
{bottom, top}
Definition at line 113 of file layer.cpp.
{
    if ((layer.bottom > pressure[0]) || (layer.top < pressure[N - 1])) {
        return {MISSING, MISSING};
    }
    float zbot = interp_pressure(layer.bottom, pressure, height, N);
    float ztop = interp_pressure(layer.top, pressure, height, N);
    if (toAGL) {
        zbot -= height[0];
        ztop -= height[0];
    }
    return {zbot, ztop};
}
References sharp::PressureLayer::bottom, height, interp_pressure(), MISSING, pressure, and sharp::PressureLayer::top.
Referenced by sharp::Parcel::cape_cinh(), entrainment_cape(), lapse_rate(), sharp_PressureLayer_to_HeightLayer(), and storm_motion_bunkers().
saturated_lift()
float sharp::saturated_lift (float pressure, float theta_sat, float converge = 0.001f)
Compute the temperature along a moist adiabat (wet-bulb potential temperature) at a given pressure.
Author
John Hart - NSSFC KCMO / NWSSPC OUN
Compute the temperature at which the moist adiabat intersects a line of constant pressure on a Skew-T log-P diagram. The wet-bulb potential temperature, given by theta_sat, defines a moist adiabat in Kelvin, and the temperature at the given pressure level in Pascals (Pa) is returned.
This function relies on the Wobus Function (sharp::wobf), and it was shown by Robert Davies-Jones (2007) that the Wobus function has a slight dependence on pressure, which results in errors of up to 1.2 Kelvin in the temperature of a lifted parcel.
Parameters
pressure (Pa)
theta_sat (K)
converge (convergence criteria; default = 0.001f)
Returns
lifted_temperature (K)
Definition at line 167 of file thermo.cpp.
{
#ifndef NO_QC
    if ((pressure == MISSING) || (theta_sat == MISSING)) {
        return MISSING;
    }
#endif
    if (std::fabs(pressure - THETA_REF_PRESSURE) <= converge) return theta_sat;
    const float pwrp = std::pow(pressure / THETA_REF_PRESSURE, ROCP);
    // get the temperature
    float t1 = theta_sat * pwrp;
    float e1 = wobf(t1) - wobf(theta_sat);
    float rate = 1.0f;
    float eor = 999;
    float t2;
    int condition = 0;
    // Testing the original showed that only
    // 5 or so iterations are needed, but
    // double that just in case. It'll exit
    // early if it converges anyway.
    for (int iter = 0; iter < 10; ++iter) {
        t2 = t1 - e1 * rate;
        float e2 = (t2) / pwrp;
        e2 = e2 + wobf(t2) - wobf(e2) - theta_sat;
        eor = e2 * rate;
        rate = (t2 - t1) / (e2 - e1);
        t1 = t2;
        e1 = e2;
        condition |= (std::fabs(eor) <= converge);
        if (condition) break;
    }
    return t2 - eor;
}
References MISSING, pressure, ROCP, THETA_REF_PRESSURE, and wobf().
Referenced by sharp_saturated_lift(), and wetlift().
significant_tornado_parameter()
float sharp::significant_tornado_parameter (Parcel pcl, float lcl_hght_agl, float storm_relative_helicity, float bulk_wind_difference)
Definition at line 254 of file convective.cpp.
{
    float cinh_term, lcl_term, shear_term, srh_term, cape_term;
    if (pcl.cape == MISSING) return MISSING;
    if (pcl.cinh >= -50.0)
        cinh_term = 1.0;
    else if (pcl.cinh < -200.0)
        cinh_term = 0.0;
    else
        cinh_term = ((200.0 + pcl.cinh) / 150.0);
    // units of comparisons are meters
    if (lcl_hght_agl < 1000.0)
        lcl_term = 1.0;
    else if (lcl_hght_agl > 2000.0)
        lcl_term = 0.0;
    else
        lcl_term = ((2000.0 - lcl_hght_agl) / 1000.0);
    // units of comparisons are m/s
    if (bulk_wind_difference > 30)
        shear_term = 1.5;
    else if (bulk_wind_difference < 12.5)
        shear_term = 0.0;
    else
        shear_term = bulk_wind_difference / 20.0;
    if (storm_relative_helicity == MISSING)
        srh_term = 0.0;
    else
        srh_term = storm_relative_helicity / 150.0;
    cape_term = pcl.cape / 1500.0;
    float stp = cape_term * cinh_term * lcl_term * srh_term * shear_term;
    if (stp < 0) stp = 0;
    return stp;
}
References sharp::Parcel::cape, sharp::Parcel::cinh, and MISSING.
Referenced by sharp_significant_tornado_parameter().
specific_humidity()
float sharp::specific_humidity (float rv)
Compute specific humidity from a mixing ratio.
Author
Kelton Halbert - NWS Storm Prediction Center
Returns the specific humidity given the mixing ratio.
Parameters
rv (kg/kg)
Returns
specific_humidity (unitless)
Definition at line 150 of file thermo.cpp.
{
#ifndef NO_QC
    if (rv == MISSING) return MISSING;
#endif
    return rv / (1.0 + rv);
}
References MISSING.
Referenced by entrainment_cape(), moist_static_energy(), and sharp_specific_humidity().
storm_motion_bunkers() [1/2]
WindComponents sharp::storm_motion_bunkers (const float pressure[], const float height[], const float u_wind[], const float v_wind[], const std::ptrdiff_t N, HeightLayer mean_wind_layer_agl, HeightLayer wind_shear_layer_agl, const bool leftMover = false, const bool pressureWeighted = false)
Estimates supercell storm motion using the Bunkers et al. 2000 method.
Author
Kelton Halbert - NWS Storm Prediction Center
Estimates supercell storm motion using the Bunkers et al. 2000 method described in the following paper: https://doi.org/10.1175/1520-0434(2000)015%3C0061:PSMUAN%3E2.0.CO;2
This does not use any of the updated methods described by Bunkers et al. 2014, which uses Effective Inflow Layer metricks to get better estimates of storm motion, especially when considering elevated convection.
Parameters
pressure (Pa)
height (meters)
u_wind (m/s)
v_wind (m/s)
N (length of arrays)
mean_wind_layer_agl {bottom, top}
wind_shear_layer_agl {bottom, top}
leftMover (default=false)
pressureWeighted (default=false)
Returns
{storm_u, storm_v}
Definition at line 37 of file convective.cpp.
{
    constexpr float deviation = 7.5;  // deviation from mean wind in m/s
    PressureLayer mw_lyr = height_layer_to_pressure(mean_wind_layer_agl,
                                                    pressure, height, N, true);
    WindComponents layer_mean_wind = {MISSING, MISSING};
    layer_mean_wind =
        mean_wind(mw_lyr, pressure, u_wind, v_wind, N, pressureWeighted);
    // The shear is computed by finding the 500m deep
    // mean winds at the top and bottom of the wind_shear_layer
    // and then differencing the two. Means are not pressure weighted
    // for the non-parcel based method.
    HeightLayer h_layer_lo = {wind_shear_layer_agl.bottom,
                              wind_shear_layer_agl.bottom + 500.0f};
    HeightLayer h_layer_hi = {wind_shear_layer_agl.top - 500.0f,
                              wind_shear_layer_agl.top};
    PressureLayer p_layer_lo =
        height_layer_to_pressure(h_layer_lo, pressure, height, N, true);
    PressureLayer p_layer_hi =
        height_layer_to_pressure(h_layer_hi, pressure, height, N, true);
    WindComponents winds_lo =
        mean_wind(p_layer_lo, pressure, u_wind, v_wind, N, false);
    WindComponents winds_hi =
        mean_wind(p_layer_hi, pressure, u_wind, v_wind, N, false);
    const float shear_u = winds_hi.u - winds_lo.u;
    const float shear_v = winds_hi.v - winds_lo.v;
    const float mag = vector_magnitude(shear_u, shear_v);
    float storm_u = MISSING;
    float storm_v = MISSING;
    if (leftMover) {
        storm_u = layer_mean_wind.u - ((deviation / mag) * shear_v);
        storm_v = layer_mean_wind.v + ((deviation / mag) * shear_u);
    } else {
        storm_u = layer_mean_wind.u + ((deviation / mag) * shear_v);
        storm_v = layer_mean_wind.v - ((deviation / mag) * shear_u);
    }
    return {storm_u, storm_v};
}
References sharp::HeightLayer::bottom, height, height_layer_to_pressure(), mean_wind(), MISSING, pressure, sharp::HeightLayer::top, sharp::WindComponents::u, sharp::WindComponents::v, and vector_magnitude().
Referenced by entrainment_cape(), sharp_storm_motion_bunkers(), sharp_storm_motion_bunkers_np(), and storm_motion_bunkers().
storm_motion_bunkers() [2/2]
WindComponents sharp::storm_motion_bunkers (const float pressure[], const float height[], const float u_wind[], const float v_wind[], const std::ptrdiff_t N, PressureLayer eff_infl_lyr, const Parcel * mupcl, const bool leftMover = false)
Estimates supercell storm motion by using the Bunkers et al. 2014 method.
Author
Kelton Halbert - NWS Storm Prediction Center
Estimates supercell storm motion using the Bunkers et al. 2014 method described in the following paper: http://dx.doi.org/10.15191/nwajom.2014.0211
This method is parcel based, using a mean-wind vector defined as the pressure-weighted mean wind between the Effective Inflow Layer surface (see sharp::effective_inflow_layer) and 65% of the depth between that surface and the most-unstable parcel's Equilibrium Level. This method produces the same storm motion estimate for surface based supercells, and captures the motion of elevated supercells much better than the Bunkers 2000 method.
The input parameters eff_infl_lyr and mupcl (effective inflow layer bounds and the most unstable parcel, respectively) are required to be be precomputed and passed to this routine. These are expensive operations that are presumed to be computed at some other point in the analysis pipeline, so just pass those variables here.
Parameters
pressure (Pa)
height (meters)
u_wind (m/s)
v_wind (m/s)
N (length of arrays)
eff_infl_lyr {bottom, top}
mupcl (Precomputed parcel)
leftMover (default=false)
Returns
{storm_u, storm_v}
Definition at line 87 of file convective.cpp.
{
    HeightLayer shr_layer = {0, 6000.0};
    HeightLayer dflt_mw_lyr = {0.0, 6000.0};
    if (mupcl->eql_pressure == MISSING) {
        return storm_motion_bunkers(pressure, height, u_wind, v_wind, N,
                                    dflt_mw_lyr, shr_layer, leftMover, false);
    }
    const float eql_pres = mupcl->eql_pressure;
    if ((eff_infl_lyr.bottom == MISSING) || (eff_infl_lyr.top == MISSING)) {
        return storm_motion_bunkers(pressure, height, u_wind, v_wind, N,
                                    dflt_mw_lyr, shr_layer, leftMover, false);
    }
    HeightLayer eil_hght =
        pressure_layer_to_height(eff_infl_lyr, pressure, height, N, true);
    float eql_ht = interp_pressure(eql_pres, pressure, height, N);
    // get AGL
    eql_ht -= height[0];
    const float htop = 0.65 * (eql_ht - eil_hght.bottom);
    if ((htop < 3000.0f) || (eil_hght.bottom > htop)) {
        return storm_motion_bunkers(pressure, height, u_wind, v_wind, N,
                                    dflt_mw_lyr, shr_layer, leftMover, false);
    }
    HeightLayer mw_layer = {eil_hght.bottom, htop};
    return storm_motion_bunkers(pressure, height, u_wind, v_wind, N, mw_layer,
                                shr_layer, leftMover, true);
}
References sharp::HeightLayer::bottom, sharp::PressureLayer::bottom, sharp::Parcel::eql_pressure, height, interp_pressure(), MISSING, pressure, pressure_layer_to_height(), storm_motion_bunkers(), and sharp::PressureLayer::top.
supercell_composite_parameter()
float sharp::supercell_composite_parameter (float mu_cape, float eff_srh, float eff_shear)
Definition at line 232 of file convective.cpp.
{
#ifndef NO_QC
    if ((mu_cape == MISSING) || (eff_srh == MISSING) ||
        (eff_shear == MISSING)) {
        return MISSING;
    }
#endif
    if (eff_shear > 20.0) {
        eff_shear = 20.0;
    } else if (eff_shear < 10.0) {
        eff_shear = 0.0;
    }
    const float mu_cape_term = mu_cape / 1000.0f;
    const float eff_srh_term = eff_srh / 50.0f;
    const float eff_shear_term = eff_shear / 20.0f;
    return mu_cape_term * eff_srh_term * eff_shear_term;
}
References MISSING.
Referenced by sharp_supercell_composite_parameter().
temperature_at_mixratio()
float sharp::temperature_at_mixratio (float wv_mixratio, float pressure)
Compute the temperature at a given water vapor mixing ratio and pressure level.
Author
Kelton Halbert - NWS Storm Prediction Center
Computes the temperature in Kelvin of air at the given water vapor mixing ratio in kg/kg and the air pressure in Pa.
The routine is implemented as in Bolton (1980) eq 11, and is considered to be accurate to 0.03 for -35C <= T <= 35C
Parameters
wv_mixratio (kg/kg)
pressure (Pa)
Returns
temperature (K)
Definition at line 87 of file thermo.cpp.
{
#ifndef NO_QC
    if ((wv_mixratio == MISSING) || (pressure == MISSING)) {
        return MISSING;
    }
#endif
    float es = (wv_mixratio / EPSILON) * pressure / 100.0f /
               (1.0 + (wv_mixratio / EPSILON));
    // for extremely cold temperatures
    es = std::min(es, pressure * 0.5f);
    const float el = std::log(es);
    return ZEROCNK + (243.5f * el - 440.8f) / (19.48f - el);
}
References EPSILON, MISSING, pressure, and ZEROCNK.
Referenced by sharp::Parcel::mixed_layer_parcel(), and sharp_temperature_at_mixratio().
theta()
float sharp::theta (float pressure, float temperature, float ref_pressure = THETA_REF_PRESSURE)
Compute the potential temperature.
Author
John Hart - NSSFC KCMO / NWSSPC OUN
Returns the potential temperature in Kelvin of a parcel given its pressure in Pascals and temperature in Kelvin. The final argument is the reference level, which is usually 100000.0 Pa, conveniently also called sharp::THETA_REF_PRESSURE.
Parameters
pressure (Pa)
temperature (K)
ref_pressure (Pa)
Returns
potential_temperature (K)
Definition at line 112 of file thermo.cpp.
{
#ifndef NO_QC
    if ((temperature == MISSING) || (pressure == MISSING) ||
        (ref_pressure == MISSING)) {
        return MISSING;
    }
#endif
    return (temperature * std::pow(ref_pressure / pressure, ROCP));
}
References MISSING, pressure, and ROCP.
Referenced by drylift(), sharp::Parcel::lift_parcel(), sharp::Parcel::mixed_layer_parcel(), moist_adiabat_cm1(), sharp_theta(), thetae(), and wetlift().
theta_level()
float sharp::theta_level (float potential_temperature, float temperature)
Comute the pressure level given potential temperature and temperature.
Author
John Hart - NSSFC KCMO / NWSSPC OUN
Returns the pressure level in Pascals (Pa) of a parcel given the potential temperature in Kelvin and the temperature of the parcel in Kelvin.
Parameters
potential_temperature (K)
temperature (K)
Returns
pressure (Pa)
Definition at line 101 of file thermo.cpp.
{
#ifndef NO_QC
    if ((potential_temperature == MISSING) || (temperature == MISSING)) {
        return MISSING;
    }
#endif
    static constexpr float CPOR = CP_DRYAIR / RDGAS;
    return THETA_REF_PRESSURE /
           std::pow((potential_temperature / temperature), CPOR);
}
References CP_DRYAIR, MISSING, RDGAS, and THETA_REF_PRESSURE.
Referenced by drylift(), and sharp_theta_level().
theta_wetbulb() [1/3]
template<typename Lft > float sharp::theta_wetbulb (Lft lifter, float pressure, float temperature, float dewpoint)
Compute the wetbulb potential temperature.
Author
John Hart - NSSFC KCMO / NWSSPC OUN
Compute the wet bulb potential temperature (K) given the pressure (Pa), temperature (K), and dewpoint (K).
First, it lifts a parcel with the given pressure, temperature, and dewpoint temperature to its Lifted Condensation Level (LCL). To compute the temperature and pressure of the LCL, an approximation is used. See the sharp::lcl_temperature documentation for more information.
After the parcel has reached the LCL, the lifter passed in lowers the parcel to the standard reference pressure level (1000.0 hPa) along a moist adiabat.
Parameters
lifter (wobf, cm1)
pressure (Pa)
temperature (K)
dewpoint (K)
Returns
wetbulb_potential_temperature (K)
Definition at line 480 of file thermo.h.
{
#ifndef NO_QC
    if ((pressure == MISSING) || (temperature == MISSING) ||
        (dewpoint == MISSING)) {
        return MISSING;
    }
#endif
    float pres_lcl = MISSING;
    float tmpk_lcl = MISSING;
    // pressure_at_lcl and temperature_at_lcl are passed by reference,
    // so the values are changed by the drylift routine
    drylift(pressure, temperature, dewpoint, pres_lcl, tmpk_lcl);
    lifter.setup(pres_lcl, tmpk_lcl);
    return lifter(pres_lcl, tmpk_lcl, THETA_REF_PRESSURE);
}
References drylift(), MISSING, pressure, and THETA_REF_PRESSURE.
Referenced by sharp_theta_wetbulb().
theta_wetbulb() [2/3]
float sharp::theta_wetbulb (lifter_cm1 lifter, float pressure, float temperature, float dewpoint)
theta_wetbulb() [3/3]
float sharp::theta_wetbulb (lifter_wobus lifter, float pressure, float temperature, float dewpoint)
thetae()
float sharp::thetae (float pressure, float temperature, float dewpoint)
Compute the equivalent potential temperature.
Author
John Hart - NSSFC KCMO / NWSSPC OUN
Compute the equivalent potential temperature (K) given the pressure (Pa), temperature (K), and dewpoint (K). The equivalent potential temperature is computed as in Bolton 1980. It was found in Davies-Jones 2009 that this is the most accurate non-iterative formulation of ThetaE.
Bolton 1980: https://doi.org/10.1175/1520-0493(1980)108%3C1046:TCOEPT%3E2.0.CO;2 Davies-Jones 2009: https://doi.org/10.1175/2009MWR2774.1
Parameters
pressure (Pa)
temperature (K)
dewpoint (K)
Returns
equivalent_potential_temperature (K)
Definition at line 384 of file thermo.cpp.
{
#ifndef NO_QC
    if ((pressure == MISSING) || (temperature == MISSING) ||
        (dewpoint == MISSING)) {
        return MISSING;
    }
#endif
    float pressure_at_lcl = MISSING;
    float temperature_at_lcl = MISSING;
    const float mixr = mixratio(pressure, dewpoint);
    const float vappres = vapor_pressure(pressure, temperature);
    // pressure_at_lcl and temperature_at_lcl are passed by reference,
    // so the values are changed by the drylift routine
    drylift(pressure, temperature, dewpoint, pressure_at_lcl,
            temperature_at_lcl);
    const float theta_lcl_dry =
        theta(pressure - vappres, temperature) *
        std::pow((temperature / temperature_at_lcl), (0.28f * mixr));
    const float thetae =
        theta_lcl_dry * std::exp(mixr * (1.0 + 0.448 * mixr) *
                                 (3036.0 / temperature_at_lcl - 1.78));
    return thetae;
}
References drylift(), MISSING, mixratio(), pressure, theta(), thetae(), and vapor_pressure().
Referenced by sharp_thetae(), and thetae().
u_component()
float sharp::u_component (float wind_speed, float wind_direction)
Computes the zonal (U) wind component from a wind vector.
Author
John Hart - NSSFC KCMO / NWSSPC OUN
Given the wind speed and direction, compute and return the zonal (U) wind component.
Parameters
wind_speed (m/s)
wind_direction (degrees from North)
Returns
u_component (m/s)
Definition at line 23 of file winds.cpp.
{
#ifndef NO_QC
    if ((wind_direction == MISSING) || (wind_speed == MISSING)) return MISSING;
#endif
    wind_direction *= (PI / 180.0);
    return -1.0 * wind_speed * std::sin(wind_direction);
}
References MISSING, and PI.
Referenced by sharp_u_component().
upper_bound()
template<typename T , typename C = std::less<>> constexpr std::ptrdiff_t sharp::upper_bound (const T array[], const std::ptrdiff_t N, const T value, const C cmp = C{}) constexpr
Finds the first index that satisfies value < element.
Author
Kelton Halbert - NWS Storm Prediction Center
Based on std::upper_bound, this iterates over an array using a binary search to find the first element that satisfies the comparison condition. By default, the comparison is std::less. Binary search expects data to be in ascending order – for pressure level data, change the comparitor.
We use a custom implementation of sharp::upper_bound rather than std::upper_bound for a few reasons. First, we prefer raw pointer arrays over vectors for easy integration with SWIG bindings, C code, and the potential future in which this runs on CUDA architecture. Currently, the algorithms in the STL library are not supported by the CUDA STL, but the types in <functional> (i.e. std::less) are supported by the CUDA STL. Additionally, this implementation of lower_bound is designed to reduce branching.
Parameters
array The array to search over
N The length of the array
value The value for upper-bound comparison
cmp The comparitor
Returns
Index of the upper bound
Definition at line 91 of file algorithms.h.
                                                                  {}) {
    std::ptrdiff_t len = N;
    std::ptrdiff_t idx = 0;
    while (len > 1) {
        std::ptrdiff_t half = len / 2;
        idx += !cmp(value, array[idx + half - 1]) * half;
        len -= half;  // = ceil(len / 2)
    }
    return idx;
}
Referenced by get_layer_index(), interp_height(), and interp_pressure().
v_component()
float sharp::v_component (float wind_speed, float wind_direction)
Computes the meridional (V) wind component from a wind vector.
Author
John Hart - NSSFC KCMO / NWSSPC OUN
Given the wind speed and direction, compute and return the meridional (V) wind component.
Parameters
wind_speed (m/s)
wind_direction (degrees from North)
Returns
v_component (m/s)
Definition at line 31 of file winds.cpp.
{
#ifndef NO_QC
    if ((wind_direction == MISSING) || (wind_speed == MISSING)) return MISSING;
#endif
    wind_direction *= (PI / 180.0);
    return -1.0 * wind_speed * std::cos(wind_direction);
}
References MISSING, and PI.
Referenced by sharp_v_component().
vapor_pressure()
float sharp::vapor_pressure (float pressure, float temperature)
Compute the vapor pressure over liquid water.
Author
Kelton Halbert - NWS Storm Prediction Center
Computes the vapor pressure (or saturation vapor pressure) in Pascals (Pa) over liquid water given the temperature in Kelvin (or dewpoint temperature in Kelvin). The air pressure is used as a minimum floor for extremely cold temperatures and low pressures.
This function uses the formulation by Bolton (1980), and is accurate to 0.3% for the temperature range of -35C <= T <= 35 C
Parameters
pressure (Pa)
temperature (K)
Returns
vapor_pressure (Pa)
Definition at line 52 of file thermo.cpp.
{
#ifndef NO_QC
    if ((temperature == MISSING) || (pressure == MISSING)) return MISSING;
#endif
    const float tmpc = temperature - ZEROCNK;
    const float es = 611.2f * std::exp(17.67f * tmpc / (temperature - 29.65f));
    // for extremely cold temperatures
    return std::min(es, pressure * 0.5f);
}
References MISSING, pressure, and ZEROCNK.
Referenced by mixratio(), sharp_vapor_pressure(), and thetae().
vapor_pressure_ice()
float sharp::vapor_pressure_ice (float pressure, float temperature)
Compute the vapor pressure over ice.
Author
Kelton Halbert - NWS Storm Prediction Center
Computes the vapor pressure (or saturation vapor pressure) in Pascals (Pa) over ice given the temperature in Kelvin (or dewpoint temperature in Kelvin). The air pressure is used as a minimum floor for extremely cold temperatures and low pressures.
This function uses the formulation by Bolton (1980), and is accurate to 0.3% for the temperature range of -35C <= T <= 35C
Parameters
pressure (Pa)
temperature (K)
Returns
vapor_pressure (Pa)
Definition at line 62 of file thermo.cpp.
{
#ifndef NO_QC
    if ((temperature == MISSING) || (pressure == MISSING)) return MISSING;
#endif
    const float tmpc = temperature - ZEROCNK;
    const float es =
        611.2f * std::exp(21.8745584f * tmpc / (temperature - 7.66f));
    // for extremely cold temperatures
    return std::min(es, pressure * 0.5f);
}
References MISSING, pressure, and ZEROCNK.
Referenced by mixratio_ice(), and sharp_vapor_pressure_ice().
vector_angle()
float sharp::vector_angle (float u_comp, float v_comp)
Computes the direction (degrees from North) a vector points to.
Author
John Hart - NSSFC KCMO / NWSSPC OUN
Given the zonal (U) and meridional (V) components of a vector, compute and return the direction (degrees from North) the vector points to.
Parameters
u_comp (m/s)
v_comp (m/s)
Returns
wind_direction (degrees from North)
Definition at line 39 of file winds.cpp.
{
#ifndef NO_QC
    if ((u_comp == MISSING) || (v_comp == MISSING)) return MISSING;
#endif
    if ((u_comp == 0) && (v_comp == 0)) return 0;
    float wind_direction =
        std::atan2(-1.0 * u_comp, -1.0 * v_comp) * (180.0 / PI);
    if (wind_direction < 0) wind_direction += 360.0;
    if (wind_direction < TOL) wind_direction = 0;
    return wind_direction;
}
References MISSING, PI, and TOL.
Referenced by components_to_vector(), and sharp_vector_angle().
vector_magnitude()
float sharp::vector_magnitude (float u_comp, float v_comp)
Computes the magnitude of a vector given its components.
Author
John Hart - NSSFC KCMO / NWSSPC OUN
Given the zonal (U) and meridional (V) components of a vector, compute and return the magnitude (m/s) of the vector.
Parameters
u_comp (m/s)
v_comp (m/s)
Returns
wind_speed (m/s)
Definition at line 52 of file winds.cpp.
{
#ifndef NO_QC
    if ((u_comp == MISSING) || (v_comp == MISSING)) return MISSING;
#endif
    return std::sqrt((u_comp * u_comp) + (v_comp * v_comp));
}
References MISSING.
Referenced by components_to_vector(), entrainment_cape(), sharp_vector_magnitude(), and storm_motion_bunkers().
vector_magnitude_precise()
float sharp::vector_magnitude_precise (float u_comp, float v_comp)
Precisely computes the magnitude of a vector given its components.
Author
John Hart - NSSFC KCMO / NWSSPC OUN
Given the zonal (U) and meridional (V) components of a vector, compute and return the magnitude (distance / time) of the vector. Instead of using a standard sqrt(u*u + v*v) approach, this uses the c++ Standard Template Library implementation of std::hypot. Using std::hypot is ~20 times slower, but ensures a higher accuracy and checks for overflow/underflow when using extremely large or extremely small values. Chances are, you are fine using the imprecise version as long as values are in the range of 1e-100 < values < 1e100.
Parameters
u_comp (m/s)
v_comp (m/s)
Returns
wind_speed (m/s)
Definition at line 59 of file winds.cpp.
{
#ifndef NO_QC
    if ((u_comp == MISSING) || (v_comp == MISSING)) return MISSING;
#endif
    return std::hypot(u_comp, v_comp);
}
References MISSING.
vector_to_components() [1/2]
WindComponents sharp::vector_to_components (float wind_speed, float wind_direction)
Conveniance function to compute the U and V components of a wind vector.
Author
Kelton Halbert - NWS Storm Prediction Center
Given the wind speed and direction of a vector, compute and return the zonal and meridional vector components as a struct.
Parameters
wind_speed (m/s)
wind_direction (degrees from North)
Returns
{u_comp, v_comp}
Definition at line 80 of file winds.cpp.
{
#ifndef NO_QC
    if ((wind_direction == MISSING) || (wind_speed == MISSING))
        return {MISSING, MISSING};
#endif
    wind_direction *= (PI / 180.0);
    const float u_comp = -1.0 * wind_speed * std::sin(wind_direction);
    const float v_comp = -1.0 * wind_speed * std::cos(wind_direction);
    return {u_comp, v_comp};
}
References MISSING, and PI.
Referenced by sharp_vector_to_components().
vector_to_components() [2/2]
WindComponents sharp::vector_to_components (WindVector vect)
Conveniance function to compute the U and V components of a wind vector.
Author
Kelton Halbert - NWS Storm Prediction Center
Given the wind speed and direction of a vector via sharp::WindVector, compute and return the zonal and meridional vector components as a struct.
Parameters
vect {speed, direction}
Returns
{u_comp, v_comp}
Definition at line 92 of file winds.cpp.
{
#ifndef NO_QC
    if ((vect.speed == MISSING) || (vect.direction == MISSING))
        return {MISSING, MISSING};
#endif
    const float wind_direction = vect.direction * (PI / 180.0);
    const float u_comp = -1.0 * vect.speed * std::sin(wind_direction);
    const float v_comp = -1.0 * vect.speed * std::cos(wind_direction);
    return {u_comp, v_comp};
}
References sharp::WindVector::direction, MISSING, PI, and sharp::WindVector::speed.
virtual_temperature()
float sharp::virtual_temperature (float temperature, float rv, float rl = 0.0f, float ri = 0.0f)
Compute the full virtual temperature.
Author
Kelton Halbert - NWS Storm Prediction Center
Returns the virtual temperature in Kelvin given the dry-bulb temperature in Kelvin, the water vapor mixing ratio (rv) in kg/kg, the liquid water mixing ratio (rl) in kg/kg, and the ice water mixing ratio (ri) in kg/kg.
For convenience, the rl and ri terms have a default value of zero to easily support returning just the virtual temperature from water vapor.
Parameters
temperature (K)
rv (kg/kg)
rl (kg/kg)
ri (kg/kg)
Returns
virtual_temperature (K)
Definition at line 157 of file thermo.cpp.
{
#ifndef NO_QC
    if ((qv == MISSING) || (ql == MISSING) || (qi == MISSING) ||
        (temperature == MISSING)) {
        return MISSING;
    }
#endif
    return (temperature * ((1.0 + (qv / EPSILON)) / (1.0 + qv + ql + qi)));
}
References EPSILON, and MISSING.
Referenced by sharp::Parcel::lift_parcel(), sharp::lifter_wobus::parcel_virtual_temperature(), sharp::lifter_cm1::parcel_virtual_temperature(), and sharp_virtual_temperature().
wetbulb() [1/3]
template<typename Lft > float sharp::wetbulb (Lft lifter, float pressure, float temperature, float dewpoint)
Compute the wetbulb temperature.
Author
John Hart - NSSFC KCMO / NWSSPC OUN
Compute the wet bulb temperature (K) given the pressure (Pa), temperature (K), and dewpoint (K).
First, it lifts a parcel with the given pressure, temperature, and dewpoint temperature to its Lifted Condensation Level (LCL). To compute the temperature and pressure of the LCL, an approximation is used. See the sharp::lcl_temperature documentation for more information.
After the parcel has reached the LCL, the lifter passed in lowers the parcel to its initial pressure level along a moist adiabat.
Parameters
lifter (cm1, wobf)
pressure (Pa)
temperature (K)
dewpoint (K)
Returns
wetbulb_temperature (K)
Definition at line 433 of file thermo.h.
{
#ifndef NO_QC
    if ((pressure == MISSING) || (temperature == MISSING) ||
        (dewpoint == MISSING)) {
        return MISSING;
    }
#endif
    float pres_lcl = MISSING;
    float tmpk_lcl = MISSING;
    // pressure_at_lcl and temperature_at_lcl are passed by reference,
    // so the values are changed by the drylift routine
    drylift(pressure, temperature, dewpoint, pres_lcl, tmpk_lcl);
    lifter.setup(pres_lcl, tmpk_lcl);
    return lifter(pres_lcl, tmpk_lcl, pressure);
}
References drylift(), MISSING, and pressure.
Referenced by sharp_wetbulb().
wetbulb() [2/3]
float sharp::wetbulb (lifter_cm1 lifter, float pressure, float temperature, float dewpoint)
wetbulb() [3/3]
float sharp::wetbulb (lifter_wobus lifter, float pressure, float temperature, float dewpoint)
wetlift()
float sharp::wetlift (float pressure, float temperature, float lifted_pressure)
Compute the temperature of a parcel lifted moist adiabatically to a new level.
Author
John Hart - NSSFC KCMO / NWSSPC OUN
With a given parcel defined by a pressure and temperature (in Pascals and Kelvin), lift it moist adiabatically to a new pressure level (in Pascals) and return the temperture of the parcel at that level.
This function relies on the Wobus Function (sharp::wobf), and it was shown by Robert Davies-Jones (2007) that the Wobus function has a slight dependence on pressure, which results in errors of up to 1.2 Kelvin in the temperature of a lifted parcel.
Parameters
pressure (Pa)
temperature (K)
lifted_pressure (Pa)
Returns
lifted_temperature (K)
Definition at line 203 of file thermo.cpp.
{
#ifndef NO_QC
    if ((temperature == MISSING) || (pressure == MISSING) ||
        (lifted_pressure == MISSING)) {
        return MISSING;
    }
#endif
    // parcels potential temperature
    const float pcl_theta = theta(pressure, temperature, THETA_REF_PRESSURE);
    // some Wobus voodo
    const float woth = wobf(pcl_theta);
    const float wott = wobf(temperature);
    // This is the wet bulb potential temperature
    const float pcl_thetaw = pcl_theta - woth + wott;
    // get the temperature that crosses the moist adiabat at
    // this pressure level
    return saturated_lift(lifted_pressure, pcl_thetaw);
}
References MISSING, pressure, saturated_lift(), theta(), THETA_REF_PRESSURE, and wobf().
Referenced by sharp::lifter_wobus::operator()(), and sharp_wetlift().
wind_shear()
template<typename L > constexpr WindComponents sharp::wind_shear (L layer, const float coord[], const float u_wind[], const float v_wind[], const std::ptrdiff_t N) constexpr
Compue the wind shear for a given layer.
Author
Kelton Halbert - NWS Storm Prediction Center
Computes the U and V components of the wind shear over a layer given the vertical sounding arrays of pressure/height, u_wind, v_wind, and their length.
This generic template handles the logic at compike time on whether or not this is a sharp::HeightLayer or a sharp::PressureLayer, and calls the interpolation routines accordingly
Parameters
layer {bottom, top}
coord (meters or Pa)
u_wind (m/s)
v_wind (m/s)
N (length of arrays)
Returns
{shear_u, shear_v}
Definition at line 262 of file winds.h.
{
#ifndef NO_QC
    if ((layer.bottom == MISSING) || (layer.top == MISSING))
        return {MISSING, MISSING};
#endif
    float u_bot = MISSING;
    float u_top = MISSING;
    float v_bot = MISSING;
    float v_top = MISSING;
    // This if statement disappears at compile time depending
    // on which kind of layer is passed
    if constexpr (layer.coord == LayerCoordinate::pressure) {
        if (layer.bottom > coord[0]) layer.bottom = coord[0];
        if (layer.top < coord[N - 1]) layer.top = coord[N - 1];
        u_bot = interp_pressure(layer.bottom, coord, u_wind, N);
        u_top = interp_pressure(layer.top, coord, u_wind, N);
        v_bot = interp_pressure(layer.bottom, coord, v_wind, N);
        v_top = interp_pressure(layer.top, coord, v_wind, N);
    } else {
        // AGL to MSL
        layer.bottom += coord[0];
        layer.top += coord[0];
        if (layer.bottom < coord[0]) layer.bottom = coord[0];
        if (layer.top > coord[N - 1]) layer.top = coord[N - 1];
        u_bot = interp_height(layer.bottom, coord, u_wind, N);
        u_top = interp_height(layer.top, coord, u_wind, N);
        v_bot = interp_height(layer.bottom, coord, v_wind, N);
        v_top = interp_height(layer.top, coord, v_wind, N);
    }
#ifndef NO_QC
    if ((u_bot == MISSING) || (v_bot == MISSING) || (u_top == MISSING) ||
        (v_top == MISSING)) {
        return {MISSING, MISSING};
    }
#endif
    return {u_top - u_bot, v_top - v_bot};
}
References interp_height(), interp_pressure(), MISSING, and pressure.
Referenced by sharp_HeightLayer_wind_shear(), and sharp_PressureLayer_wind_shear().
wobf()
float sharp::wobf (float temperature)
Computes the difference between the wet-bulb potential temperatures for saturated and dry air given the temperature.
Author
John Hart - NSSFC KCMO / NWSSPC OUN
The Wobus Function (wobf) is defined as the difference between the wet-bulb potential temperature for saturated air (WBPTS) and the wet-bulb potential temperature for dry air (WBPTD) given an input temperature in Kelvin.
WOBF(T) := WBPTS - WBPTD
Although WBPTS and WBPTD are functions of both pressure and temperature, it is assumed their difference is a function of temperature only. The difference is also proportional to the heat imparted to a parcel.
This function uses a polynomial approximation to the wobus function, fitted to values in Table 78 of PP.319-322 of the Smithsonian Meteorological Tables by Roland List (6th Revised Edition). Herman Wobus, a mathematician for the Navy Weather Research Facility in Norfolk, VA computed these coefficients a very long time ago, as he was retired as of the time of the documentation found on this routine written in 1981.
It was shown by Robert Davies-Jones (2007) that the Wobus function has a slight dependence on pressure, which results in errors of up to 1.2 Kelvin in the temperature of a lifted parcel.
Parameters
temperature (K)
Returns
wobf (K)
Definition at line 27 of file thermo.cpp.
{
#ifndef NO_QC
    if (temperature == MISSING) return MISSING;
#endif
    float pol;
    const float x = temperature - ZEROCNK - 20.0f;
    if (x <= 0.0f) {
        pol = 1.0f +
              x * (-8.841660499999999e-03f +
                   x * (1.4714143e-04f +
                        x * (-9.671989000000001e-07f +
                             x * (-3.2607217e-08f + x * (-3.8598073e-10f)))));
        pol = pol * pol;
        return (15.13f / (pol * pol)) + ZEROCNK;
    } else {
        pol = x * (4.9618922e-07f +
                   x * (-6.1059365e-09f +
                        x * (3.9401551e-11f +
                             x * (-1.2588129e-13f + x * (1.6688280e-16f)))));
        pol = 1.0f + x * (3.6182989e-03f + x * (-1.3603273e-05f + pol));
        pol = pol * pol;
        return (29.93f / (pol * pol) + 0.96f * x - 14.8f) + ZEROCNK;
    }
}
References MISSING, and ZEROCNK.
Referenced by saturated_lift(), sharp_wobf(), and wetlift().
Variable Documentation
CP_DRYAIR
constexpr float sharp::CP_DRYAIR static constexpr
Initial value:
=
    DRYAIR_SPEC_HEAT_RATIO * RDGAS / (DRYAIR_SPEC_HEAT_RATIO - 1.0f)
Definition at line 52 of file constants.h.
Referenced by _solve_cm1(), buoyancy_dilution_potential(), moist_static_energy(), and theta_level().
CP_ICE
constexpr float sharp::CP_ICE = 2118.636f static constexpr
Definition at line 59 of file constants.h.
Referenced by _solve_cm1().
CP_LIQUID
constexpr float sharp::CP_LIQUID = 4190.0f static constexpr
Definition at line 57 of file constants.h.
Referenced by _solve_cm1().
CP_VAPOR
constexpr float sharp::CP_VAPOR = 1875.0f static constexpr
Definition at line 55 of file constants.h.
Referenced by _solve_cm1().
DRYAIR_SPEC_HEAT_RATIO
constexpr float sharp::DRYAIR_SPEC_HEAT_RATIO = 1.4f static constexpr
Definition at line 26 of file constants.h.
EPSILON
constexpr float sharp::EPSILON = RDGAS / RVGAS static constexpr
Definition at line 49 of file constants.h.
Referenced by mixratio(), mixratio_ice(), temperature_at_mixratio(), and virtual_temperature().
EXP_LS
constexpr float sharp::EXP_LS = 2.836017e6f static constexpr
Definition at line 65 of file constants.h.
EXP_LV
constexpr float sharp::EXP_LV = 2.501e6f static constexpr
Definition at line 62 of file constants.h.
Referenced by moist_static_energy().
GAMMA_D
constexpr float sharp::GAMMA_D = GRAVITY / CP_DRYAIR static constexpr
Definition at line 77 of file constants.h.
GRAVITY
constexpr float sharp::GRAVITY = 9.80665f static constexpr
Definition at line 38 of file constants.h.
Referenced by buoyancy(), buoyancy_dilution_potential(), and moist_static_energy().
HPA_TO_PA
constexpr float sharp::HPA_TO_PA = 100.0f static constexpr
Definition at line 31 of file constants.h.
LS1
constexpr float sharp::LS1 = EXP_LS + (CP_ICE - CP_VAPOR) * ZEROCNK static constexpr
Definition at line 72 of file constants.h.
Referenced by _solve_cm1().
LS2
constexpr float sharp::LS2 = CP_ICE - CP_VAPOR static constexpr
Definition at line 73 of file constants.h.
Referenced by _solve_cm1().
LV1
constexpr float sharp::LV1 = EXP_LV + (CP_LIQUID - CP_VAPOR) * ZEROCNK static constexpr
Definition at line 70 of file constants.h.
Referenced by _solve_cm1().
LV2
constexpr float sharp::LV2 = CP_LIQUID - CP_VAPOR static constexpr
Definition at line 71 of file constants.h.
Referenced by _solve_cm1().
MDRY
constexpr float sharp::MDRY = 28.96546e-3f static constexpr
Definition at line 23 of file constants.h.
MISSING
constexpr float sharp::MISSING = -9999.0f static constexpr
Definition at line 36 of file constants.h.
Referenced by buoyancy_dilution_potential(), sharp::Parcel::cape_cinh(), drylift(), effective_inflow_layer(), energy_helicity_index(), entrainment_cape(), sharp::Parcel::find_lfc_el(), height_layer_to_pressure(), helicity(), integrate_layer_trapz(), interp_height(), interp_pressure(), lapse_rate(), lapse_rate_max(), layer_mean(), layer_minmax(), lcl_temperature(), mean_wind(), mixratio(), mixratio_ice(), moist_adiabat_cm1(), moist_static_energy(), pressure_layer_to_height(), saturated_lift(), sharp_entrainment_cape(), sharp_HeightLayer_get_bottom(), sharp_HeightLayer_get_top(), sharp_HeightLayer_helicity(), sharp_HeightLayer_lapse_rate(), sharp_HeightLayer_max(), sharp_HeightLayer_min(), sharp_Parcel_get_cape(), sharp_Parcel_get_cinh(), sharp_Parcel_get_dwpk(), sharp_Parcel_get_el_pres(), sharp_Parcel_get_lcl_pres(), sharp_Parcel_get_lfc_pres(), sharp_Parcel_get_pres(), sharp_Parcel_get_tmpk(), sharp_PressureLayer_get_bottom(), sharp_PressureLayer_get_top(), sharp_PressureLayer_helicity(), sharp_PressureLayer_lapse_rate(), sharp_PressureLayer_max(), sharp_PressureLayer_min(), sharp_significant_tornado_parameter(), sharp_WindComponents_get_u(), sharp_WindComponents_get_v(), sharp_WindVector_get_direction(), sharp_WindVector_get_speed(), significant_tornado_parameter(), specific_humidity(), storm_motion_bunkers(), supercell_composite_parameter(), temperature_at_mixratio(), theta(), theta_level(), theta_wetbulb(), thetae(), u_component(), v_component(), vapor_pressure(), vapor_pressure_ice(), vector_angle(), vector_magnitude(), vector_magnitude_precise(), vector_to_components(), virtual_temperature(), wetbulb(), wetlift(), wind_shear(), and wobf().
MWATER
constexpr float sharp::MWATER = 18.015268e-3f static constexpr
Definition at line 25 of file constants.h.
PA_TO_HPA
constexpr float sharp::PA_TO_HPA = 0.01f static constexpr
Definition at line 32 of file constants.h.
PI
constexpr float sharp::PI = 3.14159265f static constexpr
Definition at line 42 of file constants.h.
Referenced by entrainment_cape(), u_component(), v_component(), vector_angle(), and vector_to_components().
PRANDTL
constexpr float sharp::PRANDTL = 1.f / 3.f static constexpr
Definition at line 79 of file constants.h.
Referenced by entrainment_cape().
RDGAS
constexpr float sharp::RDGAS = RGAS / MDRY static constexpr
Definition at line 45 of file constants.h.
Referenced by _solve_cm1(), and theta_level().
RGAS
constexpr float sharp::RGAS = 8.314462618f static constexpr
Definition at line 21 of file constants.h.
ROCP
constexpr float sharp::ROCP = RDGAS / CP_DRYAIR static constexpr
Definition at line 75 of file constants.h.
Referenced by _solve_cm1(), moist_adiabat_cm1(), saturated_lift(), and theta().
RVGAS
constexpr float sharp::RVGAS = RGAS / MWATER static constexpr
Definition at line 48 of file constants.h.
Referenced by _solve_cm1().
THETA_REF_PRESSURE
constexpr float sharp::THETA_REF_PRESSURE = 100000.0f static constexpr
Definition at line 34 of file constants.h.
Referenced by drylift(), sharp::Parcel::lift_parcel(), sharp::Parcel::mixed_layer_parcel(), moist_adiabat_cm1(), saturated_lift(), theta_level(), theta_wetbulb(), and wetlift().
TOL
constexpr float sharp::TOL = 1e-10f static constexpr
Definition at line 40 of file constants.h.
Referenced by vector_angle().
VAPPRES_REF
constexpr float sharp::VAPPRES_REF = 611.65f static constexpr
Definition at line 84 of file constants.h.
VKSQ
constexpr float sharp::VKSQ = 0.18f static constexpr
Definition at line 81 of file constants.h.
Referenced by entrainment_cape().
ZEROCNK
constexpr float sharp::ZEROCNK = 273.15f static constexpr
Definition at line 29 of file constants.h.
Referenced by _solve_cm1(), temperature_at_mixratio(), vapor_pressure(), vapor_pressure_ice(), and wobf().