SPC Sounding and Hodoraph Analysis and Research Program Calculation Library: sharp::lifter_wobus Struct Reference
sharp::lifter_wobus Struct Reference
A functor that calls the Wobus Wetlift funtion.
#include <parcel.h>
Public Member Functions
void setup (const float lcl_pres, const float lcl_tmpk) const
Perform the setup step for the parcel lifter.
float operator() (const float pres, const float tmpk, const float new_pres) const
Overloads operator() to call sharp::wetlift.
float parcel_virtual_temperature (const float pres, const float tmpk) const
Computes the virtual temperature of the parcel.
Static Public Attributes
static constexpr bool lift_from_lcl = true
Detailed Description
A functor that calls the Wobus Wetlift funtion.
Author
Kelton Halbert - NWS Storm Prediction Center
This functor is used to wrap the Wobus Wetlift function for parcel lifting routines. Functors - classes with their operator() overloaded - are used so that functions can be passed to templates in a way that the compiler can still optimize, rather than using function pointers or lambdas.
Specifically, this functor is designed to be passed as a template argument to sharp::Parcel::lift_parcel, so that the method of computing moist adiabats can be changed without changing the overall parcel lifting code. The reason this is awesome is that the compiler can still optimize and inline this code, while the user can configure the parcel lifting algorithm to their specifications.
Definition at line 46 of file parcel.h.
Member Function Documentation
operator()()
float sharp::lifter_wobus::operator() (const float pres, const float tmpk, const float new_pres) const inline
Overloads operator() to call sharp::wetlift.
Parameters
pres Parcel pressure (Pa)
tmpk Parcel temperature (K)
new_pres Final level of parcel after lift (Pa)
Returns
The temperature of the lifted parcel
Definition at line 68 of file parcel.h.
{
        return wetlift(pres, tmpk, new_pres);
    }
References sharp::wetlift().
parcel_virtual_temperature()
float sharp::lifter_wobus::parcel_virtual_temperature (const float pres, const float tmpk) const inline
Computes the virtual temperature of the parcel.
Parameters
pres Parcel pressure (Pa)
tmpk Parcel temperature (K)
Returns
The virtual temperature of the parcel
Definition at line 80 of file parcel.h.
{
        return virtual_temperature(tmpk, mixratio(pres, tmpk));
    }
References sharp::mixratio(), and sharp::virtual_temperature().
setup()
void sharp::lifter_wobus::setup (const float lcl_pres, const float lcl_tmpk) const inline
Perform the setup step for the parcel lifter.
Some parcel lifters require setup in order to handle adiabatic ascent and tracking of vapor, liquid, and ice mixing ratios. The Wobus lifter does not require this, however, so this function does nothing.
Definition at line 57 of file parcel.h.
                                                                   {}
Member Data Documentation
lift_from_lcl
constexpr bool sharp::lifter_wobus::lift_from_lcl = true static constexpr
Definition at line 47 of file parcel.h.
The documentation for this struct was generated from the following file:
parcel.h