SPC Sounding and Hodoraph Analysis and Research Program Calculation Library: sharp::Parcel Struct Reference
sharp::Parcel Struct Reference
Data that defines a Parcel, its attributes, and derived quantities.
#include <parcel.h>
Public Member Functions
Parcel ()
Parcel (const float pressure, const float temperature, const float dewpoint, const LPL lpl)
template<typename Lft >
void lift_parcel (Lft &liftpcl, const float pressure_arr[], float pcl_vtmpk_arr[], const std::ptrdiff_t N)
Lifts a sharp::Parcel to compute its virtual temperature.
void find_lfc_el (const float pres_arr[], const float hght_arr[], const float buoy_arr[], const std::ptrdiff_t N)
Find the LFC and EL that bounds the layer with the maximum CAPE.
void cape_cinh (const float pres_arr[], const float hght_arr[], const float buoy_arr[], const std::ptrdiff_t N)
Compute CAPE and CINH for a previously lifted sharp::Parcel.
Static Public Member Functions
static Parcel surface_parcel (const float pressure, const float temperature, const float dewpoint) noexcept
Construct and return a surface-based Parcel.
template<typename Lyr >
static Parcel mixed_layer_parcel (Lyr &mix_layer, const float pressure[], const float height[], const float pot_temperature[], const float wv_mixratio[], const std::ptrdiff_t N) noexcept
Construct and return a mixed-layer Parcel.
template<typename Lyr , typename Lft >
static Parcel most_unstable_parcel (Lyr &search_layer, Lft &lifter, const float pressure[], const float height[], const float temperature[], const float virtemp[], const float dewpoint[], float pcl_virtemp[], float buoy_arr[], const std::ptrdiff_t N) noexcept
Construct and return a most-unstable Parcel.
Public Attributes
float pres = MISSING
Parcel starting pressure (Pa)
float tmpk = MISSING
Parcel starting temperature (K)
float dwpk = MISSING
Parcel starting dewpoint (K)
float lcl_pressure = MISSING
Pressure at the Lifted Condensation Level (Pa)
float lfc_pressure = MISSING
Pressure at the Level of Free Convection (Pa)
float eql_pressure = MISSING
Pressure at the parcel Equilibrium Level (Pa)
float cape = 0.0
Parcel Convective Available Potential Energy (J/kg) between the LFC and EL.
float cinh = 0.0
Parcel Convective Inhibition (J/kg) between the LFC and EL.
LPL source
The type of parcel this is.
Detailed Description
Data that defines a Parcel, its attributes, and derived quantities.
Author
Kelton Halbert - NWS Storm Prediction Center
Contains information about a Parcel's starting level and thermodynamic attributes, as well as paramaters computed using the parcel.
Definition at line 232 of file parcel.h.
Constructor & Destructor Documentation
Parcel() [1/2]
sharp::Parcel::Parcel ()
Definition at line 21 of file parcel.cpp.
{}
Referenced by mixed_layer_parcel(), and surface_parcel().
Parcel() [2/2]
sharp::Parcel::Parcel (const float pressure, const float temperature, const float dewpoint, const LPL lpl)
Definition at line 23 of file parcel.cpp.
{
    this->pres = pressure;
    this->tmpk = temperature;
    this->dwpk = dewpoint;
    this->source = lpl;
}
References dwpk, pres, sharp::pressure, source, and tmpk.
Member Function Documentation
cape_cinh()
void sharp::Parcel::cape_cinh (const float pres_arr[], const float hght_arr[], const float buoy_arr[], const std::ptrdiff_t N)
Compute CAPE and CINH for a previously lifted sharp::Parcel.
Author
Kelton Halbert - NWS Storm Prediction Center
Assuming that sharp::lift_parcel has been called, cape_cinh will integrate the area between the LFC and EL to compute CAPE, and integrate the area between the LPL and LCL to compute CINH.
The results are set in pcl->cape and pcl->cinh.
Parameters
pres_arr Array of pressure (Pa)
hght_arr Array of height (meters)
buoy_arr Array of buoyancy (m/s^2)
N Length of arrays
Definition at line 148 of file parcel.cpp.
{
    if (this->lcl_pressure == MISSING) return;
    find_lfc_el(pres_arr, hght_arr, buoy_arr, N);
    if ((this->lfc_pressure != MISSING) && (this->eql_pressure != MISSING)) {
        PressureLayer lfc_el = {this->lfc_pressure, this->eql_pressure};
        PressureLayer lpl_lfc = {this->pres, this->lfc_pressure};
        HeightLayer lfc_el_ht =
            pressure_layer_to_height(lfc_el, pres_arr, hght_arr, N);
        HeightLayer lpl_lfc_ht =
            pressure_layer_to_height(lpl_lfc, pres_arr, hght_arr, N);
        this->cinh =
            integrate_layer_trapz(lpl_lfc_ht, buoy_arr, hght_arr, N, -1);
        this->cape = integrate_layer_trapz(lfc_el_ht, buoy_arr, hght_arr, N, 1);
    }
}
References cape, cinh, eql_pressure, find_lfc_el(), sharp::integrate_layer_trapz(), lcl_pressure, lfc_pressure, sharp::MISSING, pres, and sharp::pressure_layer_to_height().
Referenced by sharp::effective_inflow_layer(), and most_unstable_parcel().
find_lfc_el()
void sharp::Parcel::find_lfc_el (const float pres_arr[], const float hght_arr[], const float buoy_arr[], const std::ptrdiff_t N)
Find the LFC and EL that bounds the layer with the maximum CAPE.
Author
Kelton Halbert - NWS Storm Prediction Center
Searches the buoyancy array for the LFC and EL combination that results in the most CAPE in the given profile. The buoyancy array is typically computed by calling sharp::lift_parcel. Once the LFC and EL are found, the values are set in sharp::Parcel.lfc_pres and sharp::Parcel.eql_pres.
Parameters
pres_arr The pressure coordinate array (Pa)
hght_arr The height coordinate array (meters)
buoy_arr The profile buoyancy array (m/s^2)
N The length of the arrays
Definition at line 76 of file parcel.cpp.
{
    PressureLayer sat_lyr = {this->lcl_pressure, pres_arr[N - 1]};
    LayerIndex lyr_idx = get_layer_index(sat_lyr, pres_arr, N);
    float lyr_bot = 0.0;
    float pos_buoy = 0.0;
    float pos_buoy_last = 0.0;
    float pbot = sat_lyr.bottom;
    float buoy_bot = interp_pressure(sat_lyr.bottom, pres_arr, buoy_arr, N);
    float hbot = interp_pressure(sat_lyr.bottom, pres_arr, hght_arr, N);
    // set the LFC pressure to the LCL if the buoyancy is positive
    float lfc_pres = (buoy_bot > 0) ? sat_lyr.bottom : MISSING;
    float eql_pres = MISSING;
    float lfc_pres_last = MISSING;
    float eql_pres_last = MISSING;
    for (std::ptrdiff_t k = lyr_idx.kbot; k < lyr_idx.ktop + 1; ++k) {
#ifndef NO_QC
        if (buoy_arr[k] == MISSING) continue;
#endif
        const float ptop = pres_arr[k];
        const float htop = hght_arr[k];
        const float buoy_top = buoy_arr[k];
        const float lyr_top = (buoy_top + buoy_bot) / 2.0f;
        // LFC condition
        if ((lyr_bot <= 0) && (lyr_top > 0)) {
            if (lfc_pres != MISSING) {
                pos_buoy_last = pos_buoy;
                lfc_pres_last = lfc_pres;
                eql_pres_last = eql_pres;
                pos_buoy = 0.0;
            }
            for (lfc_pres = pbot - 500; lfc_pres > ptop + 500;
                 lfc_pres -= 100.0) {
                const float buoy =
                    interp_pressure(lfc_pres, pres_arr, buoy_arr, N);
                if (buoy > 0) break;
            }
        }
        // keep track of buoyancy so that we pick the max CAPE layer
        const float condition = ((lfc_pres != MISSING) & (lyr_top > 0));
        pos_buoy += condition * lyr_top * (htop - hbot);
        // EL condition
        if ((lfc_pres != MISSING) && ((lyr_bot >= 0) && (lyr_top < 0))) {
            for (eql_pres = pbot - 500; eql_pres > ptop + 500;
                 eql_pres -= 100.0) {
                const float buoy =
                    interp_pressure(eql_pres, pres_arr, buoy_arr, N);
                if (buoy < 0) break;
            }
            if (pos_buoy_last > pos_buoy) {
                lfc_pres = lfc_pres_last;
                eql_pres = eql_pres_last;
                pos_buoy = pos_buoy_last;
            }
        }
        // If there is no EL, just use the last available level
        if ((k == N - 1) && (lyr_top > 0)) eql_pres = pres_arr[N - 1];
        // set loop variables
        pbot = ptop;
        hbot = htop;
        buoy_bot = buoy_top;
        lyr_bot = lyr_top;
    }
    if (pos_buoy > 0.0f) {
        this->lfc_pressure = lfc_pres;
        this->eql_pressure = eql_pres;
    }
}
References sharp::PressureLayer::bottom, eql_pressure, sharp::get_layer_index(), sharp::interp_pressure(), sharp::LayerIndex::kbot, sharp::LayerIndex::ktop, lcl_pressure, lfc_pressure, and sharp::MISSING.
Referenced by cape_cinh().
lift_parcel()
template<typename Lft > template void sharp::Parcel::lift_parcel< lifter_cm1 > (Lft & liftpcl, const float pressure_arr[], float pcl_vtmpk_arr[], const std::ptrdiff_t N) inline
Lifts a sharp::Parcel to compute its virtual temperature.
Author
Kelton Halbert - NWS Storm Prediction Center
Lifts a sharp::Parcel dry adiabatically from its sharp::LPL to its LCL dry adiabatically, and then moist adiabatically from the LCL to the top of the profile. The moist adiabat used is determined bu the type of lifting functor passed to the function (i.e. sharp::lifter_wobus or sharp::lifter_cm1).
Parameters
liftpcl Parcel lifting function/functor
pressure_arr Array of env pressure (Pa)
pcl_vtmpk_arr The array to fill with virtual temp (K)
N The length of the arrays
Definition at line 300 of file parcel.h.
{
        // Lift the parcel from the LPL to the LCL
        float pres_lcl;
        float tmpk_lcl;
        drylift(this->pres, this->tmpk, this->dwpk, pres_lcl, tmpk_lcl);
        // If we are lifting elevated parcel (i.e. EIL), we need to make
        // sure our LCL isnt above the top of our data.
        if (pres_lcl < pressure_arr[N - 1]) return;
        this->lcl_pressure = pres_lcl;
        const float qv_lcl = mixratio(pres_lcl, tmpk_lcl);
        const float thetav_lcl =
            theta(pres_lcl, virtual_temperature(tmpk_lcl, qv_lcl),
                  THETA_REF_PRESSURE);
        // Define the dry and saturated lift layers
        PressureLayer dry_lyr = {this->pres, this->lcl_pressure};
        PressureLayer sat_lyr = {this->lcl_pressure, pressure_arr[N - 1]};
        // The LayerIndex excludes the top and bottom for interpolation reasons
        const LayerIndex dry_idx = get_layer_index(dry_lyr, pressure_arr, N);
        const LayerIndex sat_idx = get_layer_index(sat_lyr, pressure_arr, N);
        // zero out any residual buoyancy from
        // other parcels that may have been lifted
        for (std::ptrdiff_t k = 0; k < dry_idx.kbot; ++k) {
            pcl_vtmpk_arr[k] = 0.0f;
        }
        // Virtual potential temperature (Theta-V)
        // is conserved for a parcels dry ascent to the LCL
        for (std::ptrdiff_t k = dry_idx.kbot; k < dry_idx.ktop + 1; ++k) {
            const float pcl_vtmp =
                theta(THETA_REF_PRESSURE, thetav_lcl, pressure_arr[k]);
            pcl_vtmpk_arr[k] = pcl_vtmp;
        }
        float pres_bot = pres_lcl;
        float tmpk_bot = tmpk_lcl;
        liftpcl.setup(pres_lcl, tmpk_lcl);
        // fill the array with the moist parcel buoyancy
        for (std::ptrdiff_t k = sat_idx.kbot; k < N; ++k) {
            // compute above-lcl buoyancy here
            const float pcl_pres = pressure_arr[k];
            const float pcl_tmpk = liftpcl(pres_bot, tmpk_bot, pcl_pres);
            if constexpr (!Lft::lift_from_lcl) {
                pres_bot = pcl_pres;
                tmpk_bot = pcl_tmpk;
            }
            const float pcl_vtmpk =
                liftpcl.parcel_virtual_temperature(pcl_pres, pcl_tmpk);
            pcl_vtmpk_arr[k] = pcl_vtmpk;
        }
    }
References sharp::drylift(), sharp::get_layer_index(), sharp::LayerIndex::kbot, sharp::LayerIndex::ktop, lcl_pressure, sharp::mixratio(), pres, sharp::theta(), sharp::THETA_REF_PRESSURE, and sharp::virtual_temperature().
Referenced by sharp::effective_inflow_layer(), and most_unstable_parcel().
mixed_layer_parcel()
template<typename Lyr > template Parcel sharp::Parcel::mixed_layer_parcel< HeightLayer > (Lyr & mix_layer, const float pressure[], const float height[], const float pot_temperature[], const float wv_mixratio[], const std::ptrdiff_t N) inline static noexcept
Construct and return a mixed-layer Parcel.
Author
Kelton Halbert - NWS Storm Prediction Center
Given input arrays of pressure, height, potential temperature, and water vapor mixing ratio, as well as a defined sharp::PressureLayer or sharp::HeightLayer, compute and return a mixed-layer Parcel.
Parameters
mix_layer sharp::PressureLayer or sharp::HeightLayer
pressure Array of pressure (Pa)
height Array of height (meters)
pot_temperature Array of potential temperature (K)
wv_mixratio Array of water vapor mixing ratio (unitless)
N Length of arrays
Returns
sharp::Parcel with mixed-layer values
Definition at line 438 of file parcel.h.
{
        float mean_mixr, mean_thta, pcl_pres;
        if constexpr (Lyr::coord == LayerCoordinate::pressure) {
            mean_mixr = layer_mean(mix_layer, pressure, wv_mixratio, N);
            mean_thta = layer_mean(mix_layer, pressure, pot_temperature, N);
            pcl_pres = mix_layer.bottom;
        } else {
            mean_mixr = layer_mean(mix_layer, height, pressure, wv_mixratio, N);
            mean_thta =
                layer_mean(mix_layer, height, pressure, pot_temperature, N);
            pcl_pres =
                sharp::interp_height(mix_layer.bottom, height, pressure, N);
        }
        const float tmpk = theta(THETA_REF_PRESSURE, mean_thta, pcl_pres);
        const float dwpk = temperature_at_mixratio(mean_mixr, pcl_pres);
        return Parcel(pcl_pres, tmpk, dwpk, LPL::ML);
    }
References dwpk, sharp::height, sharp::interp_height(), sharp::layer_mean(), sharp::ML, Parcel(), sharp::pressure, sharp::temperature_at_mixratio(), sharp::theta(), sharp::THETA_REF_PRESSURE, and tmpk.
most_unstable_parcel()
template<typename Lyr , typename Lft > template Parcel sharp::Parcel::most_unstable_parcel< HeightLayer, lifter_cm1 > (Lyr & search_layer, Lft & lifter, const float pressure[], const float height[], const float temperature[], const float virtemp[], const float dewpoint[], float pcl_virtemp[], float buoy_arr[], const std::ptrdiff_t N) inline static noexcept
Construct and return a most-unstable Parcel.
Author
Kelton Halbert - NWS Storm Prediction Center
Given input arrays of pressure, height, temperature, virtual temperature, and dewpoint, a scratch/working array to store values of buoyancy, and a defined sharp::PressureLayer or sharp::HeightLayer to search over, find and return the most-unstable parcel.
Parameters
pressure Array of pressure (Pa)
height Array of height (meters)
temperature Array of temperature (K)
virtemp Array of virtual temperature (K)
dewpoint Array of dewpoint temperature (K)
pcl_virtemp Writeable array for parcel lifting calcs (K)
buoy_arr Writeable array for buoyancy calcs (m/s^2)
N Length of arrays
search_layer sharp::PressureLayer or sharp::HeightLay
lifter The parcel moist adiabatic ascent function
Returns
The most unstable sharp::Parcel within the search layer
Definition at line 486 of file parcel.h.
{
        LayerIndex lyr_idx;
        if constexpr (Lyr::coord == LayerCoordinate::pressure) {
            lyr_idx = get_layer_index(search_layer, pressure, N);
        } else {
            lyr_idx = get_layer_index(search_layer, height, N);
        }
        Parcel max_parcel;
        for (std::ptrdiff_t idx = lyr_idx.kbot; idx <= lyr_idx.ktop; ++idx) {
            const float pres = pressure[idx];
            const float tmpk = temperature[idx];
            const float dwpk = dewpoint[idx];
            Parcel pcl(pres, tmpk, dwpk, LPL::MU);
            pcl.lift_parcel(lifter, pressure, pcl_virtemp, N);
            buoyancy(pcl_virtemp, virtemp, buoy_arr, N);
            pcl.cape_cinh(pressure, height, buoy_arr, N);
            if (pcl.cape > max_parcel.cape) max_parcel = pcl;
        }
        return max_parcel;
    }
References sharp::buoyancy(), cape, cape_cinh(), dwpk, sharp::get_layer_index(), sharp::height, sharp::LayerIndex::kbot, sharp::LayerIndex::ktop, lift_parcel(), sharp::MU, pres, sharp::pressure, and tmpk.
surface_parcel()
static Parcel sharp::Parcel::surface_parcel (const float pressure, const float temperature, const float dewpoint) inline static noexcept
Construct and return a surface-based Parcel.
Author
Kelton Halbert - NWS Storm Prediction Center
Given input values of surface pressure, temperature, and dewpoint temperature, construct and return a Surface Based Parcel.
Parameters
pressure Surface pressure (Pa)
temperature Surface temperature (K)
dewpoint Surface dewpoint (K)
Returns
sharp::Parcel with surface values
Definition at line 412 of file parcel.h.
{
        return Parcel(pressure, temperature, dewpoint, LPL::SFC);
    }
References Parcel(), sharp::pressure, and sharp::SFC.
Member Data Documentation
cape
float sharp::Parcel::cape = 0.0
Parcel Convective Available Potential Energy (J/kg) between the LFC and EL.
Definition at line 267 of file parcel.h.
Referenced by cape_cinh(), sharp::effective_inflow_layer(), sharp::entrainment_cape(), most_unstable_parcel(), and sharp::significant_tornado_parameter().
cinh
float sharp::Parcel::cinh = 0.0
Parcel Convective Inhibition (J/kg) between the LFC and EL.
Definition at line 272 of file parcel.h.
Referenced by cape_cinh(), sharp::effective_inflow_layer(), and sharp::significant_tornado_parameter().
dwpk
float sharp::Parcel::dwpk = MISSING
Parcel starting dewpoint (K)
Definition at line 246 of file parcel.h.
Referenced by mixed_layer_parcel(), most_unstable_parcel(), Parcel(), and sharp_define_custom_parcel().
eql_pressure
float sharp::Parcel::eql_pressure = MISSING
Pressure at the parcel Equilibrium Level (Pa)
Definition at line 261 of file parcel.h.
Referenced by cape_cinh(), sharp::entrainment_cape(), find_lfc_el(), and sharp::storm_motion_bunkers().
lcl_pressure
float sharp::Parcel::lcl_pressure = MISSING
Pressure at the Lifted Condensation Level (Pa)
Definition at line 251 of file parcel.h.
Referenced by cape_cinh(), find_lfc_el(), and lift_parcel().
lfc_pressure
float sharp::Parcel::lfc_pressure = MISSING
Pressure at the Level of Free Convection (Pa)
Definition at line 256 of file parcel.h.
Referenced by cape_cinh(), sharp::entrainment_cape(), and find_lfc_el().
pres
float sharp::Parcel::pres = MISSING
Parcel starting pressure (Pa)
Definition at line 236 of file parcel.h.
Referenced by cape_cinh(), sharp::effective_inflow_layer(), lift_parcel(), most_unstable_parcel(), Parcel(), and sharp_define_custom_parcel().
source
LPL sharp::Parcel::source
The type of parcel this is.
Definition at line 277 of file parcel.h.
Referenced by Parcel().
tmpk
float sharp::Parcel::tmpk = MISSING
Parcel starting temperature (K)
Definition at line 241 of file parcel.h.
Referenced by mixed_layer_parcel(), most_unstable_parcel(), Parcel(), and sharp_define_custom_parcel().
The documentation for this struct was generated from the following files:
parcel.h
parcel.cpp