SPC Sounding and Hodoraph Analysis and Research Program Calculation Library: sharp::lifter_cm1 Struct Reference
sharp::lifter_cm1 Struct Reference
#include <parcel.h>
Public Member Functions
void setup (const float lcl_pres, const float lcl_tmpk)
perform the necessary setup for parcel ascent.
float operator() (const float pres, const float tmpk, const float new_pres)
Overloads operator() to call sharp::moist_adiabat_cm1.
float parcel_virtual_temperature (const float pres, const float tmpk) const
Computes the virtual temperature of the parcel.
Public Attributes
adiabat ma_type = adiabat::pseudo_liq
The type of moist adiabat to use, as defined by sharp::adiabat.
float pressure_incr = 500.0f
The pressure increment (Pa) to use for the iterative solver.
float converge = 0.001f
The iterative convergence criteria (K)
Static Public Attributes
static constexpr bool lift_from_lcl = false
Private Attributes
float rv_total = MISSING
Used to keep track of mixing ratio for conserved/adiabatic lifting.
float rv = MISSING
Water vapor mixing ratio variable updated during parcel lifts.
float rl = MISSING
Liquid water mixing ratio variable updated during parcel lifts.
float ri = MISSING
Ice water mixing ratio variable updated during parcel lifts.
Detailed Description
Definition at line 86 of file parcel.h.
Member Function Documentation
operator()()
float sharp::lifter_cm1::operator() (const float pres, const float tmpk, const float new_pres) inline
Overloads operator() to call sharp::moist_adiabat_cm1.
Parameters
pres Parcel pressure (Pa)
tmpk Parcel temperature (K)
new_pres Final level of parcel after lift (Pa)
Returns
The virtual temperature of the lifted parcel
Definition at line 150 of file parcel.h.
{
        return moist_adiabat_cm1(pres, tmpk, new_pres, this->rv_total, this->rv,
                                 this->rl, this->ri, this->pressure_incr,
                                 this->converge, this->ma_type);
    }
References sharp::moist_adiabat_cm1().
parcel_virtual_temperature()
float sharp::lifter_cm1::parcel_virtual_temperature (const float pres, const float tmpk) const inline
Computes the virtual temperature of the parcel.
Parameters
pres Parcel pressure (Pa)
tmpk Parcel temperature (K)
Returns
The virtual temperature of the parcel
Definition at line 164 of file parcel.h.
{
        return virtual_temperature(tmpk, this->rv, this->rl, this->ri);
    }
References sharp::virtual_temperature().
setup()
void sharp::lifter_cm1::setup (const float lcl_pres, const float lcl_tmpk) inline
perform the necessary setup for parcel ascent.
This function sets the total water mixing ratio for adiabatic parcel ascent, and zeroes out the vapor, liquid, and ice mixing ratios from previous parcel ascents.
Definition at line 134 of file parcel.h.
{
        this->rv_total = mixratio(lcl_pres, lcl_tmpk);
        this->rv = 0.0f;
        this->rl = 0.0f;
        this->ri = 0.0f;
    }
References sharp::mixratio().
Member Data Documentation
converge
float sharp::lifter_cm1::converge = 0.001f
The iterative convergence criteria (K)
Definition at line 124 of file parcel.h.
lift_from_lcl
constexpr bool sharp::lifter_cm1::lift_from_lcl = false static constexpr
Definition at line 109 of file parcel.h.
ma_type
adiabat sharp::lifter_cm1::ma_type = adiabat::pseudo_liq
The type of moist adiabat to use, as defined by sharp::adiabat.
Definition at line 114 of file parcel.h.
pressure_incr
float sharp::lifter_cm1::pressure_incr = 500.0f
The pressure increment (Pa) to use for the iterative solver.
Definition at line 119 of file parcel.h.
ri
float sharp::lifter_cm1::ri = MISSING private
Ice water mixing ratio variable updated during parcel lifts.
Definition at line 106 of file parcel.h.
rl
float sharp::lifter_cm1::rl = MISSING private
Liquid water mixing ratio variable updated during parcel lifts.
Definition at line 101 of file parcel.h.
rv
float sharp::lifter_cm1::rv = MISSING private
Water vapor mixing ratio variable updated during parcel lifts.
Definition at line 96 of file parcel.h.
rv_total
float sharp::lifter_cm1::rv_total = MISSING private
Used to keep track of mixing ratio for conserved/adiabatic lifting.
Definition at line 91 of file parcel.h.
The documentation for this struct was generated from the following file:
parcel.h