SPC Sounding and Hodoraph Analysis and Research Program Calculation Library: thermo_wrap.h File Reference
thermo_wrap.h File Reference
Header defining the C wrapper interface to thermodynamic routines.
#include <SHARPlib/CWrap/layer_wrap.h>
Functions
float sharp_wobf (float temperature)
float sharp_vapor_pressure (float pressure, float temperature)
float sharp_vapor_pressure_ice (float pressure, float temperature)
float sharp_lcl_temperature (float temperature, float dewpoint)
float sharp_temperature_at_mixratio (float wv_mixratio, float pressure)
float sharp_theta_level (float potential_temperature, float temperature)
float sharp_theta (float pressure, float temperature, float ref_pressure)
float sharp_mixratio (float pressure, float temperature)
float sharp_mixratio_ice (float pressure, float temperature)
float sharp_specific_humidity (float q)
float sharp_virtual_temperature (float temperature, float qv, float ql, float qi)
float sharp_saturated_lift (float pressure, float theta_sat)
float sharp_wetlift (float pressure, float temperature, float lifted_pressure)
float sharp_moist_adiabat_cm1 (float pressure, float temperature, float new_pressure, float *qv_total, float *qv, float *ql, float *qi, const float pres_incr, const float converge, const int ma_type)
void sharp_drylift (float pressure, float temperature, float dewpoint, float *pressure_at_lcl, float *temperature_at_lcl)
float sharp_lifted (float pressure, float temperature, float dewpoint, float lifted_pressure)
float sharp_wetbulb (float pressure, float temperature, float dewpoint)
float sharp_theta_wetbulb (float pressure, float temperature, float dewpoint)
float sharp_thetae (float pressure, float temperature, float dewpoint)
float sharp_HeightLayer_lapse_rate (sharp_HeightLayer_t *layer_agl, const float *height, const float *temperature, const int N)
float sharp_PressureLayer_lapse_rate (sharp_PressureLayer_t *layer, const float *pressure, const float *height, const float *temperature, const int N)
float sharp_buoyancy (float pcl_temperature, float env_temperature)
float sharp_moist_static_energy (float height_agl, float temperature, float specific_humidity)
float sharp_buoyancy_dilution_potential (float temperature, float mse_bar, float saturation_mse)
Detailed Description
Header defining the C wrapper interface to thermodynamic routines.
Author
Kelton Halbert
Email: kelto.nosp@m.n.ha.nosp@m.lbert.nosp@m.@noa.nosp@m.a.gov
Date
2023-05-19
Written for the NWS Storm Prediction Center, based on NSHARP routines written by John Hart Rich Thompson.
Definition in file thermo_wrap.h.
Function Documentation
sharp_buoyancy()
float sharp_buoyancy (float pcl_temperature, float env_temperature)
Definition at line 110 of file thermo_wrap.cpp.
{
    return sharp::buoyancy(pcl_temperature, env_temperature);
}
References sharp::buoyancy().
sharp_buoyancy_dilution_potential()
float sharp_buoyancy_dilution_potential (float temperature, float mse_bar, float saturation_mse)
Definition at line 119 of file thermo_wrap.cpp.
{
    return sharp::buoyancy_dilution_potential(temperature, mse_bar,
                                              saturation_mse);
}
References sharp::buoyancy_dilution_potential().
sharp_drylift()
void sharp_drylift (float pressure, float temperature, float dewpoint, float * pressure_at_lcl, float * temperature_at_lcl)
Definition at line 70 of file thermo_wrap.cpp.
{
    if ((pressure_at_lcl == NULL) || (temperature_at_lcl == NULL)) return;
    sharp::drylift(pressure, temperature, dewpoint, *pressure_at_lcl,
                   *temperature_at_lcl);
}
References sharp::drylift().
sharp_HeightLayer_lapse_rate()
float sharp_HeightLayer_lapse_rate (sharp_HeightLayer_t * layer_agl, const float * height, const float * temperature, const int N)
Definition at line 94 of file thermo_wrap.cpp.
{
    if (layer_agl == NULL) return sharp::MISSING;
    sharp::HeightLayer* h = static_cast<sharp::HeightLayer*>(layer_agl->obj);
    return sharp::lapse_rate(*h, height, temperature, N);
}
References sharp::lapse_rate(), sharp::MISSING, and sharp_HeightLayer::obj.
sharp_lcl_temperature()
float sharp_lcl_temperature (float temperature, float dewpoint)
Definition at line 19 of file thermo_wrap.cpp.
{
    return sharp::lcl_temperature(temperature, dewpoint);
}
References sharp::lcl_temperature().
sharp_lifted()
float sharp_lifted (float pressure, float temperature, float dewpoint, float lifted_pressure)
Definition at line 77 of file thermo_wrap.cpp.
{
    return sharp::lifted(pressure, temperature, dewpoint, lifted_pressure);
}
sharp_mixratio()
float sharp_mixratio (float pressure, float temperature)
Definition at line 35 of file thermo_wrap.cpp.
{
    return sharp::mixratio(pressure, temperature);
}
References sharp::mixratio().
sharp_mixratio_ice()
float sharp_mixratio_ice (float pressure, float temperature)
Definition at line 39 of file thermo_wrap.cpp.
{
    return sharp::mixratio_ice(pressure, temperature);
}
References sharp::mixratio_ice().
sharp_moist_adiabat_cm1()
float sharp_moist_adiabat_cm1 (float pressure, float temperature, float new_pressure, float * qv_total, float * qv, float * ql, float * qi, const float pres_incr, const float converge, const int ma_type)
Definition at line 60 of file thermo_wrap.cpp.
{
    sharp::adiabat ma = static_cast<sharp::adiabat>(ma_type);
    return sharp::moist_adiabat_cm1(pressure, temperature, new_pressure,
                                    *qv_total, *qv, *ql, *qi, pres_incr,
                                    converge, ma);
}
References sharp::moist_adiabat_cm1().
sharp_moist_static_energy()
float sharp_moist_static_energy (float height_agl, float temperature, float specific_humidity)
Definition at line 114 of file thermo_wrap.cpp.
{
    return sharp::moist_static_energy(height_agl, temperature, specific_humidity);
}
References sharp::moist_static_energy().
sharp_PressureLayer_lapse_rate()
float sharp_PressureLayer_lapse_rate (sharp_PressureLayer_t * layer, const float * pressure, const float * height, const float * temperature, const int N)
Definition at line 102 of file thermo_wrap.cpp.
{
    if (layer == NULL) return sharp::MISSING;
    sharp::PressureLayer* p = static_cast<sharp::PressureLayer*>(layer->obj);
    return sharp::lapse_rate(*p, pressure, height, temperature, N);
}
References sharp::lapse_rate(), sharp::MISSING, and sharp_PressureLayer::obj.
sharp_saturated_lift()
float sharp_saturated_lift (float pressure, float theta_sat)
Definition at line 52 of file thermo_wrap.cpp.
{
    return sharp::saturated_lift(pressure, theta_sat);
}
References sharp::saturated_lift().
sharp_specific_humidity()
float sharp_specific_humidity (float q)
Definition at line 43 of file thermo_wrap.cpp.
{
    return sharp::specific_humidity(q);
}
References sharp::specific_humidity().
sharp_temperature_at_mixratio()
float sharp_temperature_at_mixratio (float wv_mixratio, float pressure)
Definition at line 23 of file thermo_wrap.cpp.
{
    return sharp::temperature_at_mixratio(wv_mixratio, pressure);
}
References sharp::temperature_at_mixratio().
sharp_theta()
float sharp_theta (float pressure, float temperature, float ref_pressure)
Definition at line 31 of file thermo_wrap.cpp.
{
    return sharp::theta(pressure, temperature, ref_pressure);
}
References sharp::theta().
sharp_theta_level()
float sharp_theta_level (float potential_temperature, float temperature)
Definition at line 27 of file thermo_wrap.cpp.
{
    return sharp::theta_level(potential_temperature, temperature);
}
References sharp::theta_level().
sharp_theta_wetbulb()
float sharp_theta_wetbulb (float pressure, float temperature, float dewpoint)
Definition at line 86 of file thermo_wrap.cpp.
{
    return sharp::theta_wetbulb(pressure, temperature, dewpoint);
}
References sharp::theta_wetbulb().
sharp_thetae()
float sharp_thetae (float pressure, float temperature, float dewpoint)
Definition at line 90 of file thermo_wrap.cpp.
{
    return sharp::thetae(pressure, temperature, dewpoint);
}
References sharp::thetae().
sharp_vapor_pressure()
float sharp_vapor_pressure (float pressure, float temperature)
Definition at line 11 of file thermo_wrap.cpp.
{
    return sharp::vapor_pressure(pressure, temperature);
}
References sharp::vapor_pressure().
sharp_vapor_pressure_ice()
float sharp_vapor_pressure_ice (float pressure, float temperature)
Definition at line 15 of file thermo_wrap.cpp.
{
    return sharp::vapor_pressure_ice(pressure, temperature);
}
References sharp::vapor_pressure_ice().
sharp_virtual_temperature()
float sharp_virtual_temperature (float temperature, float qv, float ql, float qi)
Definition at line 47 of file thermo_wrap.cpp.
{
    return sharp::virtual_temperature(temperature, qv, ql, qi);
}
References sharp::virtual_temperature().
sharp_wetbulb()
float sharp_wetbulb (float pressure, float temperature, float dewpoint)
Definition at line 82 of file thermo_wrap.cpp.
{
    return sharp::wetbulb(pressure, temperature, dewpoint);
}
References sharp::wetbulb().
sharp_wetlift()
float sharp_wetlift (float pressure, float temperature, float lifted_pressure)
Definition at line 56 of file thermo_wrap.cpp.
{
    return sharp::wetlift(pressure, temperature, lifted_pressure);
}
References sharp::wetlift().
sharp_wobf()
float sharp_wobf (float temperature)
Definition at line 7 of file thermo_wrap.cpp.
{
    return sharp::wobf(temperature);
}
References sharp::wobf().