SPC Sounding and Hodoraph Analysis and Research Program Calculation Library: winds_wrap.cpp File Reference
winds_wrap.cpp File Reference
#include <SHARPlib/CWrap/winds_wrap.h>
#include <SHARPlib/constants.h>
#include <SHARPlib/winds.h>
#include <stdlib.h>
Functions
sharp_WindVector_t * sharp_WindVector_create (float speed, float direction)
sharp_WindComponents_t * sharp_WindComponents_create (float u, float v)
void sharp_WindVector_delete (sharp_WindVector_t *v)
void sharp_WindComponents_delete (sharp_WindComponents_t *c)
float sharp_WindVector_get_speed (sharp_WindVector_t *v)
float sharp_WindVector_get_direction (sharp_WindVector_t *v)
float sharp_WindComponents_get_u (sharp_WindComponents_t *c)
float sharp_WindComponents_get_v (sharp_WindComponents_t *c)
float sharp_u_component (float wind_speed, float wind_direction)
float sharp_v_component (float wind_speed, float wind_direction)
float sharp_vector_angle (float u_comp, float v_comp)
float sharp_vector_magnitude (float u_comp, float v_comp)
void sharp_components_to_vector (sharp_WindComponents_t *comp, sharp_WindVector_t *vec)
void sharp_vector_to_components (sharp_WindVector_t *vec, sharp_WindComponents_t *comp)
void sharp_mean_wind (sharp_PressureLayer_t *plyr, sharp_WindComponents_t *cmp, const float *pres, const float *u_wind, const float *v_wind, const int N, const int weighted)
void sharp_PressureLayer_wind_shear (sharp_PressureLayer_t *plyr, sharp_WindComponents_t *cmp, const float *pres, const float *u_wind, const float *v_wind, const int N)
void sharp_HeightLayer_wind_shear (sharp_HeightLayer_t *hlyr, sharp_WindComponents_t *cmp, const float *hght, const float *u_wind, const float *v_wind, const int N)
float sharp_HeightLayer_helicity (sharp_HeightLayer_t *hlyr, sharp_WindComponents_t *storm_motion, const float *height, const float *u_wind, const float *v_wind, const int N)
float sharp_PressureLayer_helicity (sharp_PressureLayer_t *plyr, sharp_WindComponents_t *storm_motion, const float *pressure, const float *u_wind, const float *v_wind, const int N)
Function Documentation
sharp_components_to_vector()
void sharp_components_to_vector (sharp_WindComponents_t * comp, sharp_WindVector_t * vec)
Definition at line 78 of file winds_wrap.cpp.
{
    if ((comp == NULL) || (vec == NULL)) return;
    sharp::WindComponents* c = static_cast<sharp::WindComponents*>(comp->obj);
    sharp::WindVector* v = static_cast<sharp::WindVector*>(vec->obj);
    sharp::WindVector out = sharp::components_to_vector(*c);
    v->speed = out.speed;
    v->direction = out.direction;
}
References sharp::components_to_vector(), sharp::WindVector::direction, sharp_WindVector::obj, sharp_WindComponents::obj, and sharp::WindVector::speed.
sharp_HeightLayer_helicity()
float sharp_HeightLayer_helicity (sharp_HeightLayer_t * hlyr, sharp_WindComponents_t * storm_motion, const float * height, const float * u_wind, const float * v_wind, const int N)
Definition at line 134 of file winds_wrap.cpp.
{
    if ((hlyr == NULL) || (storm_motion == NULL)) return sharp::MISSING;
    sharp::HeightLayer* h = static_cast<sharp::HeightLayer*>(hlyr->obj);
    sharp::WindComponents* stm =
        static_cast<sharp::WindComponents*>(storm_motion->obj);
    return sharp::helicity(*h, *stm, height, u_wind, v_wind, N);
}
References sharp::helicity(), sharp::MISSING, sharp_HeightLayer::obj, and sharp_WindComponents::obj.
sharp_HeightLayer_wind_shear()
void sharp_HeightLayer_wind_shear (sharp_HeightLayer_t * hlyr, sharp_WindComponents_t * cmp, const float * hght, const float * u_wind, const float * v_wind, const int N)
Definition at line 122 of file winds_wrap.cpp.
{
    if ((hlyr == NULL) || (cmp == NULL)) return;
    sharp::HeightLayer* h = static_cast<sharp::HeightLayer*>(hlyr->obj);
    sharp::WindComponents* c = static_cast<sharp::WindComponents*>(cmp->obj);
    sharp::WindComponents out = sharp::wind_shear(*h, hght, u_wind, v_wind, N);
    c->u = out.u;
    c->v = out.v;
}
References sharp_HeightLayer::obj, sharp_WindComponents::obj, sharp::WindComponents::u, sharp::WindComponents::v, and sharp::wind_shear().
sharp_mean_wind()
void sharp_mean_wind (sharp_PressureLayer_t * plyr, sharp_WindComponents_t * cmp, const float * pres, const float * u_wind, const float * v_wind, const int N, const int weighted)
Definition at line 98 of file winds_wrap.cpp.
{
    if ((plyr == NULL) || (cmp == NULL)) return;
    sharp::PressureLayer* p = static_cast<sharp::PressureLayer*>(plyr->obj);
    sharp::WindComponents* c = static_cast<sharp::WindComponents*>(cmp->obj);
    sharp::WindComponents out =
        sharp::mean_wind(*p, pres, u_wind, v_wind, N, weighted);
    c->u = out.u;
    c->v = out.v;
}
References sharp::mean_wind(), sharp_PressureLayer::obj, sharp_WindComponents::obj, sharp::WindComponents::u, and sharp::WindComponents::v.
sharp_PressureLayer_helicity()
float sharp_PressureLayer_helicity (sharp_PressureLayer_t * plyr, sharp_WindComponents_t * storm_motion, const float * pressure, const float * u_wind, const float * v_wind, const int N)
Definition at line 145 of file winds_wrap.cpp.
{
    if ((plyr == NULL) || (storm_motion == NULL)) return sharp::MISSING;
    sharp::PressureLayer* p = static_cast<sharp::PressureLayer*>(plyr->obj);
    sharp::WindComponents* stm =
        static_cast<sharp::WindComponents*>(storm_motion->obj);
    return sharp::helicity(*p, *stm, pressure, u_wind, v_wind, N);
}
References sharp::helicity(), sharp::MISSING, sharp_PressureLayer::obj, and sharp_WindComponents::obj.
sharp_PressureLayer_wind_shear()
void sharp_PressureLayer_wind_shear (sharp_PressureLayer_t * plyr, sharp_WindComponents_t * cmp, const float * pres, const float * u_wind, const float * v_wind, const int N)
Definition at line 110 of file winds_wrap.cpp.
{
    if ((plyr == NULL) || (cmp == NULL)) return;
    sharp::PressureLayer* p = static_cast<sharp::PressureLayer*>(plyr->obj);
    sharp::WindComponents* c = static_cast<sharp::WindComponents*>(cmp->obj);
    sharp::WindComponents out = sharp::wind_shear(*p, pres, u_wind, v_wind, N);
    c->u = out.u;
    c->v = out.v;
}
References sharp_PressureLayer::obj, sharp_WindComponents::obj, sharp::WindComponents::u, sharp::WindComponents::v, and sharp::wind_shear().
sharp_u_component()
float sharp_u_component (float wind_speed, float wind_direction)
Definition at line 62 of file winds_wrap.cpp.
{
    return sharp::u_component(wind_speed, wind_direction);
}
References sharp::u_component().
sharp_v_component()
float sharp_v_component (float wind_speed, float wind_direction)
Definition at line 66 of file winds_wrap.cpp.
{
    return sharp::v_component(wind_speed, wind_direction);
}
References sharp::v_component().
sharp_vector_angle()
float sharp_vector_angle (float u_comp, float v_comp)
Definition at line 70 of file winds_wrap.cpp.
{
    return sharp::vector_angle(u_comp, v_comp);
}
References sharp::vector_angle().
sharp_vector_magnitude()
float sharp_vector_magnitude (float u_comp, float v_comp)
Definition at line 74 of file winds_wrap.cpp.
{
    return sharp::vector_magnitude(u_comp, v_comp);
}
References sharp::vector_magnitude().
sharp_vector_to_components()
void sharp_vector_to_components (sharp_WindVector_t * vec, sharp_WindComponents_t * comp)
Definition at line 88 of file winds_wrap.cpp.
{
    if ((vec == NULL) || (comp == NULL)) return;
    sharp::WindVector* v = static_cast<sharp::WindVector*>(vec->obj);
    sharp::WindComponents* c = static_cast<sharp::WindComponents*>(comp->obj);
    sharp::WindComponents out = sharp::vector_to_components(*v);
    c->u = out.u;
    c->v = out.v;
}
References sharp_WindVector::obj, sharp_WindComponents::obj, sharp::WindComponents::u, sharp::WindComponents::v, and sharp::vector_to_components().
sharp_WindComponents_create()
sharp_WindComponents_t * sharp_WindComponents_create (float u, float v)
Definition at line 18 of file winds_wrap.cpp.
{
    sharp_WindComponents_t* c;
    sharp::WindComponents* comp;
    c = (sharp_WindComponents_t*)malloc(sizeof(*c));
    comp = new sharp::WindComponents();
    comp->u = u;
    comp->v = v;
    c->obj = comp;
    return c;
}
References sharp_WindComponents::obj, sharp::WindComponents::u, and sharp::WindComponents::v.
sharp_WindComponents_delete()
void sharp_WindComponents_delete (sharp_WindComponents_t * c)
Definition at line 36 of file winds_wrap.cpp.
{
    if (c == NULL) return;
    delete static_cast<sharp::WindComponents*>(c->obj);
    free(c);
}
References sharp_WindComponents::obj.
sharp_WindComponents_get_u()
float sharp_WindComponents_get_u (sharp_WindComponents_t * c)
Definition at line 52 of file winds_wrap.cpp.
{
    if (c == NULL) return sharp::MISSING;
    return static_cast<sharp::WindComponents*>(c->obj)->u;
}
References sharp::MISSING, and sharp_WindComponents::obj.
sharp_WindComponents_get_v()
float sharp_WindComponents_get_v (sharp_WindComponents_t * c)
Definition at line 57 of file winds_wrap.cpp.
{
    if (c == NULL) return sharp::MISSING;
    return static_cast<sharp::WindComponents*>(c->obj)->v;
}
References sharp::MISSING, and sharp_WindComponents::obj.
sharp_WindVector_create()
sharp_WindVector_t * sharp_WindVector_create (float speed, float direction)
Definition at line 6 of file winds_wrap.cpp.
{
    sharp_WindVector_t* v;
    sharp::WindVector* vec;
    v = (sharp_WindVector_t*)malloc(sizeof(*v));
    vec = new sharp::WindVector();
    vec->speed = speed;
    vec->direction = direction;
    v->obj = vec;
    return v;
}
References sharp::WindVector::direction, sharp_WindVector::obj, and sharp::WindVector::speed.
sharp_WindVector_delete()
void sharp_WindVector_delete (sharp_WindVector_t * v)
Definition at line 30 of file winds_wrap.cpp.
{
    if (v == NULL) return;
    delete static_cast<sharp::WindVector*>(v->obj);
    free(v);
}
References sharp_WindVector::obj.
sharp_WindVector_get_direction()
float sharp_WindVector_get_direction (sharp_WindVector_t * v)
Definition at line 47 of file winds_wrap.cpp.
{
    if (v == NULL) return sharp::MISSING;
    return static_cast<sharp::WindVector*>(v->obj)->direction;
}
References sharp::MISSING, and sharp_WindVector::obj.
sharp_WindVector_get_speed()
float sharp_WindVector_get_speed (sharp_WindVector_t * v)
Definition at line 42 of file winds_wrap.cpp.
{
    if (v == NULL) return sharp::MISSING;
    return static_cast<sharp::WindVector*>(v->obj)->speed;
}
References sharp::MISSING, and sharp_WindVector::obj.